package com.yourname.expensetracker.domain.text

/**
 * Platform-agnostic message keys used by domain engines.
 * Presentation maps these keys to localized Android resources.
 */
object DomainTextKeys {
    const val COMMON_UNKNOWN = "common.unknown"
    const val COMMON_DAY_MONDAY = "common.day.monday"
    const val COMMON_DAY_TUESDAY = "common.day.tuesday"
    const val COMMON_DAY_WEDNESDAY = "common.day.wednesday"
    const val COMMON_DAY_THURSDAY = "common.day.thursday"
    const val COMMON_DAY_FRIDAY = "common.day.friday"
    const val COMMON_DAY_SATURDAY = "common.day.saturday"
    const val COMMON_DAY_SUNDAY = "common.day.sunday"

    const val ANALYTICS_HIGH_SPENDING_DESCRIPTION_FORMAT = "analytics.high_spending_description.format"
    const val ANALYTICS_WEEKEND_SPENDING_DESCRIPTION = "analytics.weekend_spending_description"
    const val ANALYTICS_GREAT_SAVINGS_DESCRIPTION_FORMAT = "analytics.great_savings_description.format"
    const val ANALYTICS_INSIGHT_SPENDING_UP_TITLE_FORMAT = "analytics.insight.spending_up.title.format"
    const val ANALYTICS_INSIGHT_SPENDING_UP_DESCRIPTION_FORMAT = "analytics.insight.spending_up.description.format"
    const val ANALYTICS_INSIGHT_SPENDING_DOWN_TITLE_FORMAT = "analytics.insight.spending_down.title.format"
    const val ANALYTICS_INSIGHT_SPENDING_DOWN_DESCRIPTION_FORMAT = "analytics.insight.spending_down.description.format"
    const val ANALYTICS_INSIGHT_PACE_WARNING_TITLE = "analytics.insight.pace_warning.title"
    const val ANALYTICS_INSIGHT_PACE_WARNING_DESCRIPTION_FORMAT = "analytics.insight.pace_warning.description.format"
    const val ANALYTICS_INSIGHT_CATEGORY_UP_TITLE_FORMAT = "analytics.insight.category_up.title.format"
    const val ANALYTICS_INSIGHT_CATEGORY_UP_DESCRIPTION_FORMAT = "analytics.insight.category_up.description.format"
    const val ANALYTICS_INSIGHT_RECURRING_TITLE_FORMAT = "analytics.insight.recurring.title.format"
    const val ANALYTICS_INSIGHT_RECURRING_DESCRIPTION_FORMAT = "analytics.insight.recurring.description.format"
    const val ANALYTICS_INSIGHT_LARGEST_TRANSACTION_TITLE_FORMAT = "analytics.insight.largest_transaction.title.format"
    const val ANALYTICS_INSIGHT_LARGEST_TRANSACTION_DESCRIPTION_FORMAT = "analytics.insight.largest_transaction.description.format"

    const val COMPUTE_MONEY_RADAR_REASON_SINGLE_BILL_DUE_FORMAT = "money_radar.reason.single_bill_due.format"
    const val COMPUTE_MONEY_RADAR_REASON_MULTIPLE_BILLS_DUE_FORMAT = "money_radar.reason.multiple_bills_due.format"
    const val COMPUTE_MONEY_RADAR_REASON_SINGLE_ANOMALY_FORMAT = "money_radar.reason.single_anomaly.format"
    const val COMPUTE_MONEY_RADAR_REASON_MULTIPLE_ANOMALIES_FORMAT = "money_radar.reason.multiple_anomalies.format"
    const val COMPUTE_MONEY_RADAR_REASON_BUDGET_RISK_CRITICAL_FORMAT = "money_radar.reason.budget_risk.critical.format"
    const val COMPUTE_MONEY_RADAR_REASON_BUDGET_RISK_HIGH_FORMAT = "money_radar.reason.budget_risk.high.format"
    const val COMPUTE_MONEY_RADAR_REASON_BUDGET_RISK_MEDIUM_FORMAT = "money_radar.reason.budget_risk.medium.format"
    const val COMPUTE_MONEY_RADAR_REASON_FINANCES_HEALTHY = "money_radar.reason.finances_healthy"
    const val COMPUTE_MONEY_RADAR_REASON_MONITOR_SPENDING = "money_radar.reason.monitor_spending"

    const val DASHBOARD_BRIEFING_OVERALL = "dashboard_briefing.overall"

    const val BUDGET_REDUCE_URGENT = "budget.reduce_urgent"
    const val BUDGET_PAUSE_NON_ESSENTIAL = "budget.pause_non_essential"
    const val BUDGET_REVIEW_SUBSCRIPTIONS = "budget.review_subscriptions"
    const val BUDGET_BUILD_HISTORY = "budget.build_history"
    const val BUDGET_EARLY_WARNING = "budget.early_warning"
    const val BUDGET_INCREASE = "budget.increase"

    const val SAVINGS_GOAL_SETTER = "savings.goal_setter"
    const val SAVINGS_WEEK_WARRIOR = "savings.week_warrior"
    const val SAVINGS_CENTURY_CLUB = "savings.century_club"
    const val SAVINGS_GOAL_CRUSHER = "savings.goal_crusher"
    const val SAVINGS_GRAND_SAVER = "savings.grand_saver"
    const val SAVINGS_ACHIEVEMENT_DESC_FIRST_GOAL = "savings.achievement.desc.first_goal"
    const val SAVINGS_ACHIEVEMENT_DESC_STREAK = "savings.achievement.desc.streak"
    const val SAVINGS_ACHIEVEMENT_DESC_SAVE_TOTAL_FORMAT = "savings.achievement.desc.save_total.format"
    const val SAVINGS_ACHIEVEMENT_DESC_COMPLETE_FIRST_GOAL = "savings.achievement.desc.complete_first_goal"
    const val SAVINGS_ACHIEVEMENT_REQ_CREATE_GOAL = "savings.achievement.req.create_goal"
    const val SAVINGS_ACHIEVEMENT_REQ_STREAK = "savings.achievement.req.streak"
    const val SAVINGS_ACHIEVEMENT_REQ_SAVED_FORMAT = "savings.achievement.req.saved.format"
    const val SAVINGS_ACHIEVEMENT_REQ_COMPLETE_GOAL = "savings.achievement.req.complete_goal"

    // Narrative section titles (NarrativeGenerator)
    const val NARRATIVE_BUDGET_ALERTS = "narrative.budget_alerts"
    const val NARRATIVE_BUDGET_HEALTH = "narrative.budget_health"
    const val NARRATIVE_GOAL_RESERVES = "narrative.goal_reserves"
    const val NARRATIVE_COMMITTED_PLANS = "narrative.committed_plans"
    const val NARRATIVE_PREDICTED_ACTIVITY = "narrative.predicted_activity"

    const val WEATHER_HEADLINE_STORMY = "weather.headline.stormy"
    const val WEATHER_SUMMARY_STORMY = "weather.summary.stormy"
    const val WEATHER_HEADLINE_RAINY = "weather.headline.rainy"
    const val WEATHER_SUMMARY_RAINY = "weather.summary.rainy"
    const val WEATHER_HEADLINE_CLOUDY = "weather.headline.cloudy"
    const val WEATHER_SUMMARY_CLOUDY_FORMAT = "weather.summary.cloudy.format"
    const val WEATHER_HEADLINE_CLEAR = "weather.headline.clear"
    const val WEATHER_SUMMARY_CLEAR_FORMAT = "weather.summary.clear.format"
    const val WEATHER_HEADLINE_PARTLY_CLOUDY = "weather.headline.partly_cloudy"
    const val WEATHER_SUMMARY_PARTLY_CLOUDY_FORMAT = "weather.summary.partly_cloudy.format"
    const val WEATHER_HEADLINE_MIXED = "weather.headline.mixed"
    const val WEATHER_SUMMARY_MIXED = "weather.summary.mixed"
    const val WEATHER_HEADLINE_UNAVAILABLE = "weather.headline.unavailable"
    const val WEATHER_SUMMARY_UNAVAILABLE = "weather.summary.unavailable"

    const val NARRATIVE_BUDGET_EXCEEDED_SPENT_FORMAT = "narrative.budget_exceeded_spent.format"
    const val NARRATIVE_TOTAL_BUDGET_EXCEEDED_SPENT_FORMAT = "narrative.total_budget_exceeded_spent.format"
    const val NARRATIVE_BUDGET_CRITICAL_SPENT_FORMAT = "narrative.budget_critical_spent.format"
    const val NARRATIVE_TOTAL_BUDGET_CRITICAL_SPENT_FORMAT = "narrative.total_budget_critical_spent.format"
    const val NARRATIVE_BUDGET_WARNING_SPENT_FORMAT = "narrative.budget_warning_spent.format"
    const val NARRATIVE_BUDGET_ON_TRACK_SPENT_FORMAT = "narrative.budget_on_track_spent.format"
    const val NARRATIVE_ALL_BUDGETS_ON_TRACK = "narrative.all_budgets_on_track"
    const val NARRATIVE_GOAL_RESERVES_LOCKED_FORMAT = "narrative.goal_reserves_locked.format"
    const val NARRATIVE_MUST_PLAN_FORMAT = "narrative.must_plan.format"
    const val NARRATIVE_LIKELY_PLAN_FORMAT = "narrative.likely_plan.format"
    const val NARRATIVE_HABIT_FORECAST_FORMAT = "narrative.habit_forecast.format"

    const val SYNTHESIS_SPENDING_PACE_HIGHER = "synthesis.spending_pace_higher"
    const val SYNTHESIS_BUDGETS_EXCEEDED_FORMAT = "synthesis.budgets_exceeded.format"
    const val SYNTHESIS_STRICT_SAVINGS_GOALS_ACTIVE_FORMAT = "synthesis.strict_savings_goals_active.format"
    const val SYNTHESIS_MUST_PAY_PLANNED_EXPENSES_FORMAT = "synthesis.must_pay_planned_expenses.format"

    const val SAVINGS_PORTFOLIO_RECOMMENDATION_READY = "savings.portfolio_recommendation_ready"
    const val SAVINGS_IMPACT_GOAL_ALREADY_REACHED = "savings.impact.goal_already_reached"
    const val SAVINGS_IMPACT_REACH_IN_DAYS_FORMAT = "savings.impact.reach_in_days.format"
    const val SAVINGS_IMPACT_ON_TRACK_MONTHS_FORMAT = "savings.impact.on_track_months.format"
    const val SAVINGS_IMPACT_STEADY_PROGRESS_FORMAT = "savings.impact.steady_progress.format"
}
