package com.yourname.expensetracker.domain.engine

import com.yourname.expensetracker.data.database.entity.Expense
import com.yourname.expensetracker.data.database.entity.AiArtifactEntity
import com.yourname.expensetracker.data.database.entity.TransactionType
import com.yourname.expensetracker.di.DefaultDispatcher
import com.yourname.expensetracker.domain.model.recommendation.DashboardFollowThroughRecommendation
import com.yourname.expensetracker.domain.model.recommendation.RecommendationPriority
import com.yourname.expensetracker.service.TransactionFilterSerializer
import com.yourname.expensetracker.ui.screens.transactions.TransactionFilter
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Engine for generating dashboard follow-through recommendations.
 * 
 * CRITICAL: This is a deterministic engine. AI only provides the `recommendationText`
 * summary. All navigation targets and filter criteria are generated by rule-based logic.
 * 
 * The engine:
 * 1. Takes transaction data + AI artifact (for summary text)
 * 2. Applies deterministic rules to generate navigation targets
 * 3. Creates TransactionFilter objects programmatically
 * 4. Returns up to 5 recommendations, sorted by priority
 */
@Singleton
class DashboardFollowThroughEngine @Inject constructor(
    private val filterSerializer: TransactionFilterSerializer,
    @DefaultDispatcher private val defaultDispatcher: CoroutineDispatcher
) {
    
    companion object {
        private const val MAX_RECOMMENDATIONS = 5
        
        // Navigation target constants
        const val NAV_TARGET_TRANSACTION_LIST = "TRANSACTION_LIST"
        const val NAV_TARGET_BUDGET_DETAIL = "BUDGET_DETAIL"
        const val NAV_TARGET_ANALYTICS = "ANALYTICS"
        const val NAV_TARGET_CATEGORY_DETAIL = "CATEGORY_DETAIL"
    }
    
    /**
     * Generate recommendations based on a transaction and AI artifact.
     * 
     * @param transaction The transaction that triggered the recommendation
     * @param aiArtifact AI artifact containing the summary text (AI-generated)
     * @param userId User identifier
     * @return List of recommendations (up to 5, sorted by priority)
     */
    suspend fun generateRecommendations(
        transaction: Expense,
        aiArtifact: AiArtifactEntity?,
        userId: String
    ): List<DashboardFollowThroughRecommendation> {
        return withContext(defaultDispatcher) {
            val recommendations = mutableListOf<DashboardFollowThroughRecommendation>()
            
            // Rule 1: High-amount transaction recommendation
            if (transaction.amount > 100.0) {
                recommendations.add(
                    createHighAmountRecommendation(transaction, aiArtifact, userId)
                )
            }
            
            // Rule 2: Category-specific recommendation
            if (transaction.categoryId != null) {
                recommendations.add(
                    createCategoryRecommendation(transaction, aiArtifact, userId)
                )
            }
            
            // Rule 3: Merchant-specific recommendation
            if (!transaction.merchant.isNullOrBlank()) {
                recommendations.add(
                    createMerchantRecommendation(transaction, aiArtifact, userId)
                )
            }
            
            // Rule 4: Recent transactions recommendation (last 7 days)
            recommendations.add(
                createRecentTransactionsRecommendation(transaction, aiArtifact, userId)
            )
            
            // Sort by priority and take top 5
            recommendations
                .sortedWith(compareByDescending<DashboardFollowThroughRecommendation> { it.priority.rank() })
                .take(MAX_RECOMMENDATIONS)
        }
    }
    
    /**
     * Generate recommendations from analytics insight.
     * This is called when AI generates an insight about spending patterns.
     */
    suspend fun generateFromInsight(
        insightText: String,
        categoryId: Long?,
        dateRangeStart: Long,
        dateRangeEnd: Long,
        priority: RecommendationPriority,
        userId: String,
        sourceArtifactId: String = ""
    ): DashboardFollowThroughRecommendation {
        return withContext(defaultDispatcher) {
            val filter = TransactionFilter(
                categoryId = categoryId,
                dateRange = Pair(dateRangeStart, dateRangeEnd)
            )
            
            val filterJson = filterSerializer.serialize(filter)
            
            DashboardFollowThroughRecommendation(
                userId = userId,
                recommendationText = insightText,
                navigationTarget = NAV_TARGET_TRANSACTION_LIST,
                filterCriteria = filterJson,
                priority = priority,
                category = categoryId?.toString() ?: "GENERAL",
                sourceArtifactId = sourceArtifactId
            )
        }
    }
    
    // Private helper methods for creating specific recommendation types
    
    private fun createHighAmountRecommendation(
        transaction: Expense,
        aiArtifact: AiArtifactEntity?,
        userId: String
    ): DashboardFollowThroughRecommendation {
        val recommendationText = aiArtifact?.summaryText 
            ?: "Large transaction detected: ${transaction.merchant ?: "Unknown"} - €${String.format("%.2f", transaction.amount)}"
        
        // Filter: Show all transactions >= this amount in the same category
        val filter = TransactionFilter(
            categoryId = transaction.categoryId,
            minAmount = transaction.amount,
            transactionType = transaction.transactionType
        )
        
        val filterJson = filterSerializer.serialize(filter)
        
        return DashboardFollowThroughRecommendation(
            userId = userId,
            recommendationText = recommendationText,
            navigationTarget = NAV_TARGET_TRANSACTION_LIST,
            filterCriteria = filterJson,
            priority = RecommendationPriority.HIGH,
            category = transaction.categoryId?.toString() ?: "GENERAL",
            sourceArtifactId = aiArtifact?.id?.toString() ?: ""
        )
    }
    
    private fun createCategoryRecommendation(
        transaction: Expense,
        aiArtifact: AiArtifactEntity?,
        userId: String
    ): DashboardFollowThroughRecommendation {
        val recommendationText = aiArtifact?.summaryText
            ?: "Review all transactions in this category"
        
        // Filter: Show all transactions in this category for the last 30 days
        val nowMillis = System.currentTimeMillis()
        val thirtyDaysAgo = nowMillis - (30L * 24 * 60 * 60 * 1000)
        
        val filter = TransactionFilter(
            categoryId = transaction.categoryId,
            dateRange = Pair(thirtyDaysAgo, nowMillis),
            transactionType = TransactionType.PURCHASE
        )
        
        val filterJson = filterSerializer.serialize(filter)
        
        return DashboardFollowThroughRecommendation(
            userId = userId,
            recommendationText = recommendationText,
            navigationTarget = NAV_TARGET_CATEGORY_DETAIL,
            filterCriteria = filterJson,
            priority = RecommendationPriority.MEDIUM,
            category = transaction.categoryId?.toString() ?: "GENERAL",
            sourceArtifactId = aiArtifact?.id?.toString() ?: ""
        )
    }
    
    private fun createMerchantRecommendation(
        transaction: Expense,
        aiArtifact: AiArtifactEntity?,
        userId: String
    ): DashboardFollowThroughRecommendation {
        val merchantName = transaction.merchant ?: "Unknown"
        val recommendationText = aiArtifact?.summaryText
            ?: "Review all transactions from $merchantName"
        
        // Filter: Show all transactions from this merchant
        val filter = TransactionFilter(
            merchantName = merchantName
        )
        
        val filterJson = filterSerializer.serialize(filter)
        
        return DashboardFollowThroughRecommendation(
            userId = userId,
            recommendationText = recommendationText,
            navigationTarget = NAV_TARGET_TRANSACTION_LIST,
            filterCriteria = filterJson,
            priority = RecommendationPriority.MEDIUM,
            category = transaction.categoryId?.toString() ?: "GENERAL",
            sourceArtifactId = aiArtifact?.id?.toString() ?: ""
        )
    }
    
    private fun createRecentTransactionsRecommendation(
        transaction: Expense,
        aiArtifact: AiArtifactEntity?,
        userId: String
    ): DashboardFollowThroughRecommendation {
        val recommendationText = aiArtifact?.summaryText
            ?: "Review your recent spending this week"
        
        // Filter: Show all transactions from the last 7 days
        val nowMillis = System.currentTimeMillis()
        val sevenDaysAgo = nowMillis - (7L * 24 * 60 * 60 * 1000)
        
        val filter = TransactionFilter(
            dateRange = Pair(sevenDaysAgo, nowMillis),
            transactionType = TransactionType.PURCHASE
        )
        
        val filterJson = filterSerializer.serialize(filter)
        
        return DashboardFollowThroughRecommendation(
            userId = userId,
            recommendationText = recommendationText,
            navigationTarget = NAV_TARGET_TRANSACTION_LIST,
            filterCriteria = filterJson,
            priority = RecommendationPriority.LOW,
            category = "GENERAL",
            sourceArtifactId = aiArtifact?.id?.toString() ?: ""
        )
    }

    private fun RecommendationPriority.rank(): Int = when (this) {
        RecommendationPriority.HIGH -> 3
        RecommendationPriority.MEDIUM -> 2
        RecommendationPriority.LOW -> 1
    }
}
