#!/usr/bin/env python3
"""
Fix test compilation errors for named-parameter constructor calls only.
This handles the most common pattern: ViewModels with named params that need
a new constructor parameter added.

Usage:
  python fix_named_only.py
  
Reads errors from fresh_errors.txt (generated by gradle compile)
"""
import re
import os
import json

TEST_DIR = r"C:\Users\panos\Desktop\cost agregator\ExpenseTracker\app\src\test\java\com\yourname\expensetracker"
ERROR_FILE = r"C:\Users\panos\.local\share\opencode\tool-output\fresh_errors.txt"

# Parse errors from file
def parse_errors():
    errors = []
    error_pattern = re.compile(
        r"e:\s*file:///C:.*?expensetracker/(.+?):(\d+):\d+\s+"
        r"No value passed for parameter '(\w+)'"
    )
    try:
        with open(ERROR_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                m = error_pattern.search(line)
                if m:
                    rel_path = m.group(1).replace('%20', ' ')
                    line_num = int(m.group(2))
                    param_name = m.group(3)
                    abs_path = os.path.join(TEST_DIR, rel_path)
                    errors.append((abs_path, line_num, param_name))
    except FileNotFoundError:
        print(f"Error file not found: {ERROR_FILE}")
        return []
    return errors

# Parameter fix definitions
PARAM_DEFS = {
    "currencySettingsRepository": {
        "decl": '    private val currencySettingsRepository = mockk<CurrencySettingsRepository>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.currency.CurrencySettingsRepository',
    },
    "timeProvider": {
        "decl": '    private val timeProvider = FakeTimeProvider()',
        "import": None,
    },
    "currencyConverter": {
        "decl": '    private val currencyConverter = mockk<CurrencyConverter>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.currency.CurrencyConverter',
    },
    "privacyGate": {
        "decl": '    private val privacyGate = mockk<PrivacyGate>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.privacy.PrivacyGate',
    },
    "multiCurrencyRepository": {
        "decl": '    private val multiCurrencyRepository = mockk<MultiCurrencyRepository>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.data.repository.MultiCurrencyRepository',
    },
    "analyticsCurrencyNormalizer": {
        "decl": '    private val analyticsCurrencyNormalizer = mockk<AnalyticsCurrencyNormalizer>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.analytics.AnalyticsCurrencyNormalizer',
    },
    "receiptLifecycleCoordinator": {
        "decl": '    private val receiptLifecycleCoordinator = mockk<ReceiptLifecycleCoordinator>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.receipt.lifecycle.ReceiptLifecycleCoordinator',
    },
    "receiptLinkService": {
        "decl": '    private val receiptLinkService = mockk<ReceiptLinkService>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.receipt.lifecycle.ReceiptLinkService',
    },
    "categoryRepository": {
        "decl": '    private val categoryRepository = mockk<CategoryRepository>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.data.repository.CategoryRepository',
    },
    "expenseRepository": {
        "decl": '    private val expenseRepository = mockk<ExpenseRepository>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.data.repository.ExpenseRepository',
    },
    "cashFlowCalculator": {
        "decl": '    private val cashFlowCalculator = mockk<CashFlowCalculator>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.cashflow.CashFlowCalculator',
    },
    "restoreMaintenanceMode": {
        "decl": '    private val restoreMaintenanceMode = mockk<RestoreMaintenanceMode>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.data.backup.RestoreMaintenanceMode',
    },
    "recurringLifecycleCoordinator": {
        "decl": '    private val recurringLifecycleCoordinator = mockk<RecurringLifecycleCoordinator>(relaxed = true)',
        "import": None,
    },
    "recurringOccurrenceDao": {
        "decl": '    private val recurringOccurrenceDao = mockk<RecurringOccurrenceDao>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.data.database.dao.RecurringOccurrenceDao',
    },
    "coordinator": {
        "decl": '    private val coordinator = mockk<TransactionLifecycleCoordinator>(relaxed = true)',
        "import": 'import com.yourname.expensetracker.domain.transaction.lifecycle.TransactionLifecycleCoordinator',
    },
    "legacyDataMigrationService": {
        "decl": '    private val legacyDataMigrationService = mockk<LegacyDataMigrationService>(relaxed = true)',
        "import": None,
    },
    "receiptParser": {
        "decl": '    private val receiptParser = mockk<ReceiptParser>(relaxed = true)',
        "import": None,
    },
    "forecastInputAssembler": {
        "decl": '    private val forecastInputAssembler = mockk<ForecastInputAssembler>(relaxed = true)',
        "import": None,
    },
    "anomalyAlertRepository": {
        "decl": '    private val anomalyAlertRepository = mockk<AnomalyAlertRepository>(relaxed = true)',
        "import": None,
    },
    "monthlySavingsSweepUseCase": {
        "decl": '    private val monthlySavingsSweepUseCase = mockk<MonthlySavingsSweepUseCase>(relaxed = true)',
        "import": None,
    },
    "recurringPatternsProvider": {
        "decl": '    private val recurringPatternsProvider = mockk<RecurringPatternsProvider>(relaxed = true)',
        "import": None,
    },
    "hybridExpenseClassifier": {
        "decl": '    private val hybridExpenseClassifier = mockk<HybridExpenseClassifier>(relaxed = true)',
        "import": None,
    },
    "categorizationEngine": {
        "decl": '    private val categorizationEngine = mockk<CategorizationEngine>(relaxed = true)',
        "import": None,
    },
    "notificationService": {
        "decl": '    private val notificationService = mockk<NotificationService>(relaxed = true)',
        "import": None,
    },
}

def add_import(content, import_line):
    if import_line is None or import_line in content:
        return content
    lines = content.split('\n')
    last_import = -1
    for i, line in enumerate(lines):
        if line.startswith('import '):
            last_import = i
        elif line.startswith('package ') or line == '':
            continue
        elif last_import >= 0:
            break
    if last_import >= 0:
        lines.insert(last_import + 1, import_line)
    elif last_import == -1:
        # No imports exist, add after package
        for i, line in enumerate(lines):
            if line.startswith('package '):
                lines.insert(i + 1, '')
                lines.insert(i + 2, import_line)
                break
    return '\n'.join(lines)

def add_field(content, decl):
    if decl is None:
        return content
    lines = content.split('\n')
    # Check if already present
    param_name = decl.split('=')[0].strip().split()[-1] if '=' in decl else ''
    for line in lines:
        if param_name and ('val ' + param_name in line or 'var ' + param_name in line):
            return content
    
    # Find insertion point: after last field declaration
    insert_idx = None
    for i, line in enumerate(lines):
        if re.match(r'^\s+private (val|var|lateinit var) \w+', line):
            insert_idx = i + 1
    if insert_idx is None:
        for i, line in enumerate(lines):
            if re.match(r'^\s*(override fun setup|@Before|fun setup)', line):
                insert_idx = i
    if insert_idx is None:
        for i, line in enumerate(lines):
            if re.match(r'^class ', line):
                insert_idx = i + 1
    
    if insert_idx is not None:
        lines.insert(insert_idx, decl)
    
    return '\n'.join(lines)

def is_named_param_constructor(lines, start_idx):
    """Check if a constructor at start_idx uses named parameters."""
    # The line should match: variable = ClassName(
    # And the following lines should have: param = value
    if start_idx + 1 >= len(lines):
        return False
    
    for j in range(start_idx + 1, min(start_idx + 10, len(lines))):
        line = lines[j]
        if ')' in line and line.strip() == ')':
            break
        if re.match(r'^\s+\w+\s*=', line):
            return True
    
    return False

def find_constructor_end(lines, start_idx):
    """Find the index of the closing paren for a multi-line constructor."""
    depth = 1
    for j in range(start_idx + 1, len(lines)):
        depth += lines[j].count('(') - lines[j].count(')')
        if depth <= 0:
            return j
    return len(lines) - 1

def fix_file(file_errors):
    """Fix all named-parameter constructor errors in a file."""
    if not file_errors:
        return 0
    
    abs_path = file_errors[0][0]
    if not os.path.exists(abs_path):
        print(f"  SKIP: {abs_path} not found")
        return 0
    
    with open(abs_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # Step 1: Group errors by param name to add imports and fields
    param_names = set(e[2] for e in file_errors)
    params_added = set()
    
    for param_name in param_names:
        if param_name not in PARAM_DEFS:
            continue
        if param_name in params_added:
            continue
        
        defn = PARAM_DEFS[param_name]
        
        # Add import
        content = add_import(content, defn["import"])
        
        # Add field declaration
        if defn["decl"]:
            new_content = add_field(content, defn["decl"])
            if new_content != content:
                params_added.add(param_name)
                content = new_content
    
    # Step 2: Fix constructor calls
    lines = content.split('\n')
    
    # For each error with a named-param constructor, find and fix the constructor
    for abs_path, line_num, param_name in file_errors:
        if param_name not in PARAM_DEFS:
            continue
        
        # The error line (0-indexed) points to the START of the constructor
        # But line_num is 1-indexed from the error log
        idx = line_num - 1
        
        if idx >= len(lines):
            continue
        
        # Check if this is a named-param constructor
        line = lines[idx]
        
        # Look for pattern: variable = ClassName(
        if not re.match(r'^(\s*)(\w+)\s*=\s*(\w+)\s*\($', line) and not re.match(r'^(\s*)(\w+)\s*=\s*(\w+)\s*\(', line):
            # This line might not be the constructor start - try nearby
            # Look backwards a bit
            found = False
            for lookback in range(min(idx, 5), 0, -1):
                if re.match(r'^(\s*)(\w+)\s*=\s*(\w+)\s*\($', lines[idx - lookback]) or \
                   re.match(r'^(\s*)(\w+)\s*=\s*(\w+)\s*\(', lines[idx - lookback]):
                    idx = idx - lookback
                    line = lines[idx]
                    found = True
                    break
            
            if not found:
                continue
        
        if not is_named_param_constructor(lines, idx):
            # Try looking at the NEXT line too
            if idx + 1 < len(lines) and is_named_param_constructor(lines, idx):
                pass
            else:
                # This is likely a positional constructor - skip for now
                continue
        
        # Find the constructor end
        end_idx = find_constructor_end(lines, idx)
        
        # Get constructor text
        constr_lines = lines[idx:end_idx + 1]
        constr_text = '\n'.join(constr_lines)
        
        # Check if param already in this constructor
        if param_name in constr_text:
            continue
        
        # Check if param_value (same as param_name) is already in this constructor
        param_value = param_name
        if param_value in constr_text:
            continue
        
        # Add the param before the closing paren
        # Find the indent level
        indent_match = re.match(r'^(\s*)', line)
        indent = indent_match.group(1) if indent_match else ''
        inner_indent = indent + '    '
        
        new_line = inner_indent + param_name + " = " + param_value
        
        # Insert before closing paren (line end_idx)
        # First check if there's already content on the closing line
        closing_line = lines[end_idx]
        if closing_line.strip() == ')':
            lines.insert(end_idx, new_line)
            end_idx += 1  # Because we inserted before
        else:
            # Multi-line constructor might have content after ) 
            # Split the line at the )
            paren_pos = closing_line.index(')')
            before_paren = closing_line[:paren_pos]
            after_paren = closing_line[paren_pos:]
            if before_paren.strip():
                # There's content before ), like: arg3)
                # Add comma to this line and add new param before )
                lines[end_idx] = before_paren.rstrip() + ','
                lines.insert(end_idx + 1, new_line)
                lines[end_idx + 2] = indent + ')' + after_paren.lstrip(')')
            else:
                # Just whitespace before )
                lines[end_idx] = new_line
                lines.insert(end_idx + 1, indent + ')')
                end_idx += 1
    
    content = '\n'.join(lines)
    
    if content != original:
        with open(abs_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return len(params_added)
    
    return 0

def main():
    errors = parse_errors()
    print(f"Found {len(errors)} missing-param errors")
    
    # Group by file
    file_map = {}
    for abs_path, line_num, param_name in errors:
        if abs_path not in file_map:
            file_map[abs_path] = []
        file_map[abs_path].append((abs_path, line_num, param_name))
    
    print(f"Errors in {len(file_map)} files")
    
    total_fixed = 0
    total_files = 0
    
    for abs_path, file_errors in file_map.items():
        fixed = fix_file(file_errors)
        if fixed > 0:
            total_fixed += fixed
            total_files += 1
            basename = os.path.basename(abs_path)
            fixed_params = list(set(e[2] for e in file_errors if e[2] in PARAM_DEFS))
            print(f"  FIXED {fixed_params} in {basename}")
        else:
            pass  # Skip unchanged files
    
    print(f"\nFixed {total_files} files with {total_fixed} new params")

if __name__ == "__main__":
    main()
