package com.yourname.expensetracker.domain.diagnostics

enum class DiagnosticReasonCode {
    PRIVACY_DENIED,
    PRIVACY_FAIL_CLOSED,
    RESTORE_BLOCKED,
    WRITE_BARRIER_DENIED,
    READ_BARRIER_DENIED,
    FILTER_REJECTED,
    BLOCKED_PACKAGE,
    DUPLICATE,
    VALIDATION_FAILED,
    PARSER_FAILED,
    OCR_FAILED,
    MISSING_RATE,
    STALE_RATE,
    PERMISSION_DENIED,
    NOTIFICATION_PERMISSION_DENIED,
    NETWORK_UNAVAILABLE,
    PROVIDER_DISABLED,
    TOKEN_INVALID,
    CANCELLED_BY_SYSTEM,
    CANCELLED_BY_USER,
    SIDE_EFFECT_EXCEPTION,
    SOURCE_LINK_FAILED,
    UNKNOWN_ERROR,
    STOP_REQUESTED,
    TIMEOUT
}
