package com.yourname.expensetracker.domain.sideeffect

enum class SideEffectTriggerType {
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    EXPENSE_BULK_UPDATED,
    RECEIPT_SAVED,
    RECEIPT_LINKED,
    RECEIPT_UNLINKED,
    RECURRING_OCCURRENCE_PAID,
    RECURRING_RULE_UPDATED,
    REMINDER_CLAIMED,
    BUDGET_UPDATED,
    FORECAST_GENERATED,
    IMPORT_COMPLETED,
    BANK_SYNC_COMPLETED,
    WORKER_COMPLETED
}
