package com.yourname.expensetracker.domain.transaction

enum class LifecycleEventType {
    CREATE_ATTEMPTED,
    CREATED,
    CREATE_VALIDATION_FAILED,
    CREATE_DUPLICATE_SKIPPED,
    CREATE_INSERT_CONFLICT,
    UPDATED,
    BULK_UPDATED,
    DELETED,
    UPDATE_VALIDATION_FAILED,
    DEBUG_DELETE_ALL_EXPENSES,
    RESTORED_FROM_DEBUG_SNAPSHOT,
    SOURCE_LINKED,
    SIDE_EFFECT_FAILED,
    GROUP_ARCHIVED,
    GROUP_PERMANENT_DELETE_ATTEMPTED,
    GROUP_PERMANENT_DELETE_BLOCKED,
    GROUP_PERMANENTLY_DELETED,
    BULK_DELETED
}
