package com.yourname.expensetracker.domain.forecasting

// RESOLVED (P6-P1-3): ForecastInput now carries ForecastDataQuality with isPartial,
// confidencePenalty, excluded counts, and conversionWarnings. Downstream engines
// (SynthesisEngine) should apply dataQuality.confidencePenalty to final confidence scores.

import com.yourname.expensetracker.data.database.dao.RecurringOccurrenceDao
import com.yourname.expensetracker.data.database.entity.ManualRecurringExpense
import com.yourname.expensetracker.data.database.entity.RecurringOccurrence
import com.yourname.expensetracker.data.database.entity.PlannedExpensePriority as EntityPlannedExpensePriority
import com.yourname.expensetracker.data.database.entity.TransactionType
import com.yourname.expensetracker.data.database.entity.TransferDirection
import com.yourname.expensetracker.domain.analytics.AnalyticsConversionWarningType
import com.yourname.expensetracker.domain.analytics.AnalyticsCurrencyNormalizer
import com.yourname.expensetracker.domain.analytics.PaceStatus
import com.yourname.expensetracker.domain.analytics.SpendingPace
import com.yourname.expensetracker.domain.analytics.SpendingPaceProjection
import com.yourname.expensetracker.domain.budget.BudgetStatus
import com.yourname.expensetracker.domain.currency.CurrencySettingsRepository
import com.yourname.expensetracker.domain.model.ConfirmedOccurrence
import com.yourname.expensetracker.domain.model.DomainTransactionType
import com.yourname.expensetracker.domain.model.DomainTransferDirection
import com.yourname.expensetracker.domain.model.ExpenseSnapshot
import com.yourname.expensetracker.domain.model.PlannedExpense
import com.yourname.expensetracker.domain.model.PlannedExpensePriority as DomainPlannedExpensePriority
import com.yourname.expensetracker.domain.model.RecurringPattern
import com.yourname.expensetracker.domain.model.SavingsGoal
import com.yourname.expensetracker.domain.logic.RecurrenceCalculator
import com.yourname.expensetracker.domain.model.dashboard.BudgetStatusSnapshot
import com.yourname.expensetracker.domain.recurring.lifecycle.RecurringLifecycleCoordinator
import com.yourname.expensetracker.domain.util.MerchantKeyGenerator
import com.yourname.expensetracker.domain.currency.CurrencyConverter
import com.yourname.expensetracker.domain.util.TimePeriodUtils
import com.yourname.expensetracker.domain.util.TimeProvider
import kotlinx.coroutines.flow.first
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.roundToLong
import timber.log.Timber

/**
 * Single source of truth for forecast-input assembly used by weather/dashboard forecast paths.
 *
 * Recurring merge policy (canonical):
 * - include all manual recurring rows
 * - include detected recurring rows only when confidence >= [HIGH_CONFIDENCE_THRESHOLD]
 * - dedupe restored stale manual rows by stable rule signature, not merchant alone
 * - manual rows take precedence only for the same stable rule signature
 *
 * ## Double-count risk (RESOLVED)
 *
 * Planned expenses that link to a recurring occurrence (via sourceOccurrenceKey)
 * are cross-deduplicated against materialized occurrences in the forecast window.
 * If a planned expense's sourceOccurrenceKey matches any PLANNED or PAID occurrence
 * generated by [RecurringLifecycleCoordinator.generateOccurrences], the planned
 * expense is excluded to avoid double-counting. Detected-only patterns (those
 * without manual rule counterparts) still flow through independently.
 *
 * ## FCST-10: Payday detection for income timing (planned)
 * Currently income timing uses a simple uniform spread, which produces inaccurate
 * cash-flow forecasts. The plan is to add payday detection that analyzes historical
 * deposit patterns:
 *
 * 1. **Identify recurring deposits**: Scan expenses with `transactionType = DEPOSIT`
 *    and group by source (payor name / merchant / transfer source).
 * 2. **Detect periodicity**: For each source, compute inter-deposit intervals and
 *    detect the dominant frequency (weekly, biweekly, semi-monthly, monthly).
 *    Use autocorrelation or FFT to identify the period even with modest jitter.
 * 3. **Predict next deposit**: Given the detected cadence and the last known deposit
 *    date, project the next expected deposit date and amount (using the rolling
 *    average of recent deposits from that source).
 * 4. **Integrate into forecast**: Add predicted deposits to [ForecastInput] as
 *    "income occurrences" so the [SynthesisEngine] can factor income timing into
 *    daily balance projections. Income confidence should decay for sources with
 *    fewer than 3 prior deposits.
 *
 * The detection logic belongs in a new `PaydayDetector` class; this assembler
 * would call it during [assemble] and merge the results into the forecast input.
 */
@Singleton
class ForecastInputAssembler @Inject constructor(
    private val timeProvider: TimeProvider,
    private val analyticsCurrencyNormalizer: AnalyticsCurrencyNormalizer,
    private val currencySettingsRepository: CurrencySettingsRepository,
    private val currencyConverter: CurrencyConverter,
    /** @suppress Coordinator injected for occurrence-driven dedup. */
    private val recurringLifecycleCoordinator: RecurringLifecycleCoordinator,
    /** @suppress DAO injected to query materialized occurrences for dedup. */
    private val recurringOccurrenceDao: RecurringOccurrenceDao
) {
    /**
     * REC-20: Effective amount stability in recurring forecasting.
     *
     * All expense aggregation in this assembler uses [ExpenseSnapshot.effectiveAmount]
     * rather than the raw [ExpenseSnapshot.amount]. This is critical for stability
     * in recurring expense calculations because:
     *
     * - Shared expenses (group bills, split payments) have their per-person portion
     *   in [effectiveAmount], while [amount] is the full bill. Using the raw amount
     *   would overcount the user's actual recurring obligation.
     * - "Not mine" expenses ([isNotMine]) yield an effective amount of 0.0,
     *   correctly excluding them from totals without special-case logic.
     * - The derived [effectiveAmount] is deterministic for a given set of ownership
     *   flags, producing stable forecast baselines even when the raw `amount` field
     *   changes due to currency conversion or rounding.
     *
     * Always prefer [effectiveAmount] over [amount] when computing recurring
     * forecasts, budget projections, and spending trends.
     */

    data class ForecastInput(
        val pastSumDaily: List<Double>,
        val recurringPatterns: List<RecurringPattern>,
        val plannedExpenses: List<PlannedExpense>,
        val savingsGoals: List<SavingsGoal>,
        val budgetStatuses: List<BudgetStatusSnapshot>,
        val spendingPace: SpendingPace,
        /**
         * Materialised occurrences from manual recurring rules within the forecast window.
         * Downstream consumers (SynthesisEngine) should use this for accurate
         * per-occurrence committed/likely calculations instead of estimating
         * WEEKLY/BIWEEKLY counts from a single [RecurringPattern.nextExpectedDate].
         */
        val confirmedOccurrences: List<ConfirmedOccurrence> = emptyList(),
        val displayCurrency: String = "",
        val dataQuality: ForecastDataQuality = ForecastDataQuality()
    )

    fun mapExpenseSnapshots(
        expenses: List<com.yourname.expensetracker.data.database.entity.Expense>
    ): List<ExpenseSnapshot> = expenses.map { expense ->
        ExpenseSnapshot(
            id = expense.id,
            amount = expense.amount,
            effectiveAmount = expense.effectiveAmount,
            currency = expense.currency,
            merchant = expense.merchant,
            merchantKey = expense.merchantKey,
            transactionType = when (expense.transactionType) {
                TransactionType.PURCHASE -> DomainTransactionType.PURCHASE
                TransactionType.WITHDRAWAL -> DomainTransactionType.WITHDRAWAL
                TransactionType.TRANSFER -> DomainTransactionType.TRANSFER
                TransactionType.DEPOSIT -> DomainTransactionType.DEPOSIT
                TransactionType.UNKNOWN -> DomainTransactionType.UNKNOWN
            },
            date = expense.date,
            categoryId = expense.categoryId,
            isNotMine = expense.isNotMine,
            transferDirection = when (expense.transferDirection) {
                TransferDirection.INCOMING -> DomainTransferDirection.INCOMING
                TransferDirection.OUTGOING -> DomainTransferDirection.OUTGOING
                null -> null
            },
            notes = expense.notes
        )
    }

    /**
     * Maps entity [PlannedExpense] rows to domain [PlannedExpense] objects.
     *
     * ## FCST-1: Exclude FULFILLED planned expenses
     * Planned expenses with status == "FULFILLED" have already been linked to an
     * actual expense and must be excluded from forecast input to prevent
     * double-counting. Since the domain model does not carry a status field,
     * the filter is applied here at the mapping boundary.
     */
    fun mapPlannedExpenses(
        plannedEntities: List<com.yourname.expensetracker.data.database.entity.PlannedExpense>
    ): List<PlannedExpense> = plannedEntities
        .filter { entity -> entity.status == "PLANNED" }
        .map { entity ->
            PlannedExpense(
                id = entity.id,
                description = entity.description,
                amount = entity.amount,
                currency = entity.currency,
                date = entity.date,
                categoryId = entity.categoryId,
                isRecurring = entity.isRecurring,
                priority = when (entity.priority) {
                    EntityPlannedExpensePriority.MUST -> DomainPlannedExpensePriority.MUST
                    EntityPlannedExpensePriority.LIKELY -> DomainPlannedExpensePriority.LIKELY
                    EntityPlannedExpensePriority.OPTIONAL -> DomainPlannedExpensePriority.OPTIONAL
                },
                sourceOccurrenceKey = entity.sourceOccurrenceKey,
                status = entity.status
            )
        }

    fun mapBudgetSnapshots(budgetStatuses: List<BudgetStatus>): List<BudgetStatusSnapshot> =
        budgetStatuses.map { status ->
            BudgetStatusSnapshot(
                budgetCategoryId = status.budget.categoryId,
                budgetAmount = status.effectiveLimit,
                categoryName = status.category?.name,
                spentAmount = status.spentAmount,
                remainingAmount = status.remainingAmount,
                percentUsed = status.percentUsed.toDouble(),
                healthStatus = status.healthStatus,
                periodStart = status.periodStart,
                periodEnd = status.periodEnd
            )
        }

    fun mapSavingsGoals(goals: List<SavingsGoal>): List<SavingsGoal> = goals

    fun mergeRecurringPatterns(
        manualEntities: List<ManualRecurringExpense>,
        detectedPatterns: List<RecurringPattern>
    ): List<RecurringPattern> {
        val manualPatterns = mapConfirmedRecurringPatterns(manualEntities)

        val deduplicatedManualPatterns = dedupeManualPatternsBySignature(manualPatterns)
        val manualRuleSignatures = deduplicatedManualPatterns
            .mapTo(mutableSetOf()) { recurringRuleSignature(it) }
        val acceptedDetected = detectedPatterns
            .asSequence()
            .filter { it.confidence >= HIGH_CONFIDENCE_THRESHOLD }
            .filter { pattern -> recurringRuleSignature(pattern) !in manualRuleSignatures }
            .toList()

        // TODO P2-20: Merged patterns retain their original currency amounts. SynthesisEngine
        //  sums them raw without normalization to home currency. The proper fix requires
        //  injecting CurrencyConverter and converting each pattern's averageAmount to home
        //  currency here, which is tracked in the master plan as a larger refactor.
        return (deduplicatedManualPatterns + acceptedDetected).sortedByDescending { it.confidence }
    }

    fun mapConfirmedRecurringPatterns(
        manualEntities: List<ManualRecurringExpense>
    ): List<RecurringPattern> {
        val now = timeProvider.now()
        return manualEntities.map { manual ->
            RecurringPattern(
                id = manual.id,
                merchantName = manual.merchant,
                averageAmount = manual.amount,
                currency = manual.currency,
                frequency = manual.frequency,
                nextExpectedDate = rollNextExpectedDateForward(
                    nextExpectedDate = manual.nextDate,
                    frequency = manual.frequency,
                    now = now
                ),
                confidence = 1.0f,
                periodVarianceDays = 0,
                amountVariancePercent = 0.0,
                previousDates = emptyList()
            )
        }
    }

    fun dedupeConfirmedRecurringPatterns(
        manualPatterns: List<RecurringPattern>
    ): List<RecurringPattern> = dedupeManualPatternsBySignature(manualPatterns)

    private fun dedupeManualPatternsBySignature(
        manualPatterns: List<RecurringPattern>
    ): List<RecurringPattern> {
        return manualPatterns
            .groupBy { manualPatternSignature(it) }
            .values
            .map { patternsForSignature ->
                patternsForSignature.maxWithOrNull(
                    compareBy<RecurringPattern> { it.nextExpectedDate }
                        .thenBy { it.id ?: Long.MIN_VALUE }
                        .thenBy { it.merchantName }
                ) ?: patternsForSignature.first()
            }
    }

    private fun manualPatternSignature(pattern: RecurringPattern): ManualPatternSignature {
        return ManualPatternSignature(
            ruleSignature = recurringRuleSignature(pattern),
            categoryId = pattern.categoryId
        )
    }

    private fun recurringRuleSignature(pattern: RecurringPattern): RecurringRuleSignature {
        return RecurringRuleSignature(
            merchantKey = merchantKey(pattern.merchantName),
            frequency = pattern.frequency,
            amountMinor = (pattern.averageAmount * 100.0).roundToLong(),
            currency = pattern.currency.uppercase()
        )
    }

    fun buildPastSumDaily(expenses: List<ExpenseSnapshot>): List<Double> {
        val now = timeProvider.now()
        val monthStart = TimePeriodUtils.getStartOfMonth(now)
        val currentDayIndex = TimePeriodUtils.daysBetween(monthStart, now).coerceAtLeast(0)
        val amountByDay = DoubleArray(currentDayIndex + 1)

        expenses.forEach { expense ->
            if (expense.transactionType != DomainTransactionType.PURCHASE) return@forEach
            if (expense.isNotMine) return@forEach
            if (expense.date !in monthStart..now) return@forEach

            val dayIndex = TimePeriodUtils.daysBetween(monthStart, expense.date)
            if (dayIndex in amountByDay.indices) {
                amountByDay[dayIndex] += expense.effectiveAmount
            }
        }

        var runningTotal = 0.0
        return amountByDay.map { amount ->
            runningTotal += amount
            runningTotal
        }
    }

    fun buildSpendingPace(expenses: List<ExpenseSnapshot>, displayCurrency: String = "EUR"): SpendingPace {
        val now = timeProvider.now()
        val currentMonthStart = TimePeriodUtils.getStartOfMonth(now)
        val previousMonthStart = TimePeriodUtils.getStartOfMonth(TimePeriodUtils.addMonths(now, -1))
        val daysInMonth = TimePeriodUtils.getDaysInMonth(now)
        val daysElapsed = (TimePeriodUtils.daysBetween(currentMonthStart, now) + 1).coerceAtLeast(1)

        val monthSpent = expenses.sumOfIfOwnedPurchase { it.date in currentMonthStart..now }
        val previousMonthSpent = expenses.sumOfIfOwnedPurchase {
            it.date >= previousMonthStart && it.date < currentMonthStart
        }

        val averageMonthlyTotal = expenses
            .filter {
                it.transactionType == DomainTransactionType.PURCHASE &&
                    !it.isNotMine &&
                    it.date < currentMonthStart
            }
            .groupBy { "${TimePeriodUtils.getYear(it.date)}-${TimePeriodUtils.getMonth(it.date)}" }
            .values
            // SAFE: data normalized via AnalyticsCurrencyNormalizer at line 299 (inside assemble())
            .map { monthExpenses -> monthExpenses.sumOf { it.effectiveAmount } }
            .takeIf { it.isNotEmpty() }
            ?.average()

        val previousMonthDays = TimePeriodUtils.getDaysInMonth(previousMonthStart)
        val baselineDailyRate = if (previousMonthSpent > 0.0 && previousMonthDays > 0) {
            previousMonthSpent / previousMonthDays
        } else {
            0.0
        }

        val projectedTotal = SpendingPaceProjection.calculateProjectedTotal(
            monthSpent = monthSpent,
            daysElapsed = daysElapsed,
            daysInMonth = daysInMonth,
            baselineDailyRate = baselineDailyRate
        )

        val currentDailyRate = monthSpent / daysElapsed
        val pacePercentage = if (baselineDailyRate > 0.0) {
            (currentDailyRate / baselineDailyRate * 100.0).toFloat()
        } else {
            0f
        }

        val paceStatus = when {
            baselineDailyRate <= 0.0 -> PaceStatus.NO_BASELINE
            pacePercentage < PACE_UNDER_THRESHOLD -> PaceStatus.UNDER_PACE
            pacePercentage > PACE_OVER_THRESHOLD -> PaceStatus.OVER_PACE
            else -> PaceStatus.ON_PACE
        }

        return SpendingPace(
            currentMonthSpent = monthSpent,
            daysElapsed = daysElapsed,
            daysInMonth = daysInMonth,
            projectedTotal = projectedTotal,
            previousMonthTotal = previousMonthSpent.takeIf { it > 0.0 },
            averageMonthlyTotal = averageMonthlyTotal,
            pacePercentage = pacePercentage,
            paceStatus = paceStatus,
            displayCurrency = displayCurrency
        )
    }

    suspend fun assemble(
        expenses: List<ExpenseSnapshot>,
        manualRecurringEntities: List<ManualRecurringExpense>,
        detectedRecurringPatterns: List<RecurringPattern>,
        plannedExpenses: List<PlannedExpense>,
        savingsGoals: List<SavingsGoal>,
        budgetStatuses: List<BudgetStatusSnapshot>,
        homeCurrency: String? = null
    ): ForecastInput {
        val resolvedHomeCurrency = try {
            homeCurrency ?: currencySettingsRepository.homeCurrency().first()
        } catch (e: Exception) {
            Timber.w(e, "ForecastInputAssembler: failed to resolve home currency, falling back to EUR")
            "EUR"
        }
        val normalized = analyticsCurrencyNormalizer.normalizeSnapshots(expenses, resolvedHomeCurrency)
        val normalizedExpenses = normalized.includedExpenses

        // Generate concrete occurrences for active manual recurring rules
        val now = timeProvider.now()
        val forecastStart = TimePeriodUtils.getStartOfMonth(now)
        val forecastEnd = TimePeriodUtils.getEndOfMonth(now)
        for (rule in manualRecurringEntities) {
            if (!rule.isActive) continue
            try {
                recurringLifecycleCoordinator.generateOccurrences(
                    ruleId = rule.id,
                    startDate = forecastStart,
                    endDate = forecastEnd
                )
            } catch (e: Exception) {
                // Non-fatal: if one rule fails to generate, continue with the rest
            }
        }

        // ── Query materialized occurrences for dedup + confirmed occurrences ──
        // Get all occurrences in the forecast window. These serve two purposes:
        // 1) Build a set of occurrenceKeys for planned-expense cross-dedup
        // 2) Provide full occurrence data for downstream occurrence-driven forecasting
        val materializedOccurrences: List<RecurringOccurrence> = try {
            recurringOccurrenceDao.getByDateRange(forecastStart, forecastEnd)
        } catch (e: Exception) {
            emptyList()
        }
        val materializedOccurrenceKeys = materializedOccurrences
            .filter { it.status == "PLANNED" }
            .map { it.occurrenceKey }.toSet()
        val confirmedOccurrences = materializedOccurrences
            .filter { it.status == "PLANNED" }
            .map { occ ->
                ConfirmedOccurrence(
                    dueDate = occ.dueDate,
                    expectedAmount = occ.expectedAmount,
                    expectedCurrency = occ.expectedCurrency,
                    merchant = occ.merchant,
                    categoryId = occ.categoryId,
                    status = occ.status
                )
            }

        val deduplicatedPlannedExpenses = plannedExpenses.filterNot { planned ->
            planned.sourceOccurrenceKey != null &&
                planned.sourceOccurrenceKey in materializedOccurrenceKeys
        }

        // ── Planned expense quality tracking ──────────────────────────────────
        val plannedDedupExcluded = plannedExpenses.size - deduplicatedPlannedExpenses.size
        var plannedConversionFailures = 0
        val plannedWarnings = mutableListOf<String>()

        // Normalize planned expenses: attempt conversion to home currency for each.
        // Expenses that fail conversion are excluded from the forecast (they would
        // produce incorrect amounts in a different currency).
        val normalizedPlannedExpenses = deduplicatedPlannedExpenses.mapNotNull { pe ->
            if (pe.currency.equals(resolvedHomeCurrency, ignoreCase = true)) {
                pe.copy(amount = pe.amount, currency = resolvedHomeCurrency)
            } else {
                val normalized = currencyConverter.convert(
                    amount = pe.amount,
                    fromCurrency = pe.currency,
                    toCurrency = resolvedHomeCurrency
                )
                if (normalized != null) {
                    pe.copy(amount = normalized.convertedAmount, currency = resolvedHomeCurrency)
                } else {
                    plannedConversionFailures++
                    plannedWarnings.add("Planned expense '${pe.description}' ${pe.amount} ${pe.currency} excluded — conversion failed")
                    null
                }
            }
        }

        val totalPlannedExcluded = plannedDedupExcluded + plannedConversionFailures

        val inputCount = normalized.totalInputCount
        val excludedCount = normalized.excludedCount
        val missingRateWarnings = normalized.warnings.filter {
            it.type == AnalyticsConversionWarningType.MISSING_EXCHANGE_RATE
        }
        val confidencePenalty = if (inputCount > 0) {
            val excludedRatio = excludedCount.toDouble() / inputCount
            val missingRatio = missingRateWarnings.size.toDouble() / inputCount
            (excludedRatio * 0.35 + missingRatio * 0.10).coerceIn(0.0, 0.50)
        } else 0.0

        return ForecastInput(
            pastSumDaily = buildPastSumDaily(normalizedExpenses),
            recurringPatterns = mergeRecurringPatterns(
                manualEntities = manualRecurringEntities,
                detectedPatterns = detectedRecurringPatterns
            ),
            plannedExpenses = normalizedPlannedExpenses,
            savingsGoals = savingsGoals,
            budgetStatuses = budgetStatuses,
            spendingPace = buildSpendingPace(normalizedExpenses, resolvedHomeCurrency),
            confirmedOccurrences = confirmedOccurrences,
            displayCurrency = resolvedHomeCurrency,
            dataQuality = ForecastDataQuality(
                isPartial = excludedCount > 0 || totalPlannedExcluded > 0,
                confidencePenalty = confidencePenalty,
                excludedActualCount = excludedCount,
                excludedPlannedCount = totalPlannedExcluded,
                excludedRecurringCount = 0,
                conversionWarnings = normalized.warnings.map { warning ->
                    "${warning.type.name}: ${warning.message}"
                } + plannedWarnings
            )
        )
    }

    /**
     * FCST-N3-FIXED: Consistent merchantKey fallback.
     *
     * Returns a stable merchant key for deduplication. When MerchantKeyGenerator
     * returns blank (e.g. because the merchant name is null or empty), we fall
     * back to the lowercase trimmed merchant name. This ensures that the fallback
     * is self-consistent across ALL forecast paths:
     *
     * - Forecast path A (Weather/FinancialWeatherRepository) uses this method
     *   via [recurringRuleSignature] → [merchantKey].
     * - Forecast path B (CalculateFinancialForecastUseCase) also uses the same
     *   [recurringRuleSignature] → [merchantKey] path.
     * - Expense-level merchant keys come from [ExpenseSnapshot.merchantKey]
     *   which was stored at write time via [MerchantKeyGenerator.generate].
     *
     * Both paths now converge on the same fallback logic. The previous
     * inconsistency occurred because some callers used `merchantKey ?: merchant`
     * (falling back to the raw merchant name) while others used
     * `MerchantKeyGenerator.generate(merchantName)` alone, leading to
     * different signature values for the same logical merchant.
     */
    private fun merchantKey(merchantName: String): String {
        return MerchantKeyGenerator.generate(merchantName)
            .takeIf { it.isNotBlank() }
            ?: merchantName.lowercase().trim()
    }

    private fun rollNextExpectedDateForward(
        nextExpectedDate: Long,
        frequency: com.yourname.expensetracker.domain.model.RecurrenceFrequency,
        now: Long
    ): Long {
        if (frequency.isIrregular) return nextExpectedDate

        val todayStart = TimePeriodUtils.getStartOfDay(now)
        var rolledDate = nextExpectedDate
        while (rolledDate < todayStart) {
            val candidate = RecurrenceCalculator.addFrequencyInterval(rolledDate, frequency)
            if (candidate == rolledDate) break
            rolledDate = candidate
        }

        return rolledDate
    }

    private fun List<ExpenseSnapshot>.sumOfIfOwnedPurchase(
        predicate: (ExpenseSnapshot) -> Boolean
    ): Double = filter {
        it.transactionType == DomainTransactionType.PURCHASE &&
            !it.isNotMine &&
            predicate(it)
    }
        // SAFE: data normalized via AnalyticsCurrencyNormalizer at line 299 (inside assemble())
        .sumOf { it.effectiveAmount }

    /**
     * CURR-587-06: Assemble forecast input from pre-normalized data.
     *
     * This bypasses the AnalyticsCurrencyNormalizer step since the expenses
     * are already normalized to home currency. The SpendingPace is also
     * taken directly from the input rather than recomputed.
     */
    suspend fun assembleNormalized(
        input: NormalizedForecastInput
    ): ForecastInput {
        return ForecastInput(
            pastSumDaily = input.pastSumDaily,
            recurringPatterns = input.recurringPatterns,
            plannedExpenses = input.plannedExpenses,
            savingsGoals = input.savingsGoals,
            budgetStatuses = input.budgetStatuses,
            spendingPace = input.spendingPace,
            confirmedOccurrences = emptyList(), // Can be populated via occurrence DAO if needed
            displayCurrency = input.homeCurrency.code,
            dataQuality = input.dataQuality
        )
    }

    companion object {
        const val HIGH_CONFIDENCE_THRESHOLD: Float = 0.70f
        private const val PACE_UNDER_THRESHOLD = 90f
        private const val PACE_OVER_THRESHOLD = 110f
    }

    private data class ManualPatternSignature(
        val ruleSignature: RecurringRuleSignature,
        val categoryId: Long?
    )

    private data class RecurringRuleSignature(
        val merchantKey: String,
        val frequency: com.yourname.expensetracker.domain.model.RecurrenceFrequency,
        val amountMinor: Long,
        val currency: String
    )
}
