package com.yourname.expensetracker.domain.forecasting

// RESOLVED (P6-P1-3): ForecastInput now carries ForecastDataQuality with isPartial,
// confidencePenalty, excluded counts, and conversionWarnings. Downstream engines
// (SynthesisEngine) should apply dataQuality.confidencePenalty to final confidence scores.

import com.yourname.expensetracker.data.backup.DatabaseReadBarrier
import com.yourname.expensetracker.data.database.dao.RecurringOccurrenceDao
import com.yourname.expensetracker.data.database.entity.ManualRecurringExpense
import com.yourname.expensetracker.data.database.entity.RecurringOccurrence
import com.yourname.expensetracker.data.database.entity.PlannedExpensePriority as EntityPlannedExpensePriority
import com.yourname.expensetracker.data.database.entity.TransactionType
import com.yourname.expensetracker.data.database.entity.TransferDirection
import com.yourname.expensetracker.domain.analytics.AnalyticsConversionWarningType
import com.yourname.expensetracker.domain.analytics.AnalyticsCurrencyNormalizer
import com.yourname.expensetracker.domain.analytics.PaceStatus
import com.yourname.expensetracker.domain.analytics.SpendingPace
import com.yourname.expensetracker.domain.analytics.SpendingPaceProjection
import com.yourname.expensetracker.domain.budget.BudgetStatus
import com.yourname.expensetracker.domain.currency.CurrencySettingsRepository
import com.yourname.expensetracker.domain.model.ConfirmedOccurrence
import com.yourname.expensetracker.domain.model.DomainTransactionType
import com.yourname.expensetracker.domain.model.DomainTransferDirection
import com.yourname.expensetracker.domain.model.ExpenseSnapshot
import com.yourname.expensetracker.domain.model.PlannedExpense
import com.yourname.expensetracker.domain.model.PlannedExpensePriority as DomainPlannedExpensePriority
import com.yourname.expensetracker.domain.model.RecurringPattern
import com.yourname.expensetracker.domain.model.SavingsGoal
import com.yourname.expensetracker.domain.logic.RecurrenceCalculator
import com.yourname.expensetracker.domain.model.dashboard.BudgetStatusSnapshot
import com.yourname.expensetracker.domain.recurring.lifecycle.RecurringLifecycleCoordinator
import com.yourname.expensetracker.domain.util.MerchantKeyGenerator
import com.yourname.expensetracker.domain.core.money.BucketDatePolicy
import com.yourname.expensetracker.domain.core.money.CurrencyCode
import com.yourname.expensetracker.domain.core.money.MoneyNormalizationEngine
import com.yourname.expensetracker.domain.core.money.RateBasis
import com.yourname.expensetracker.domain.core.money.MoneyBucketInput
import com.yourname.expensetracker.domain.currency.CurrencyConverter
import com.yourname.expensetracker.domain.util.TimePeriodUtils
import com.yourname.expensetracker.domain.util.TimeProvider
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.roundToLong

/**
 * Single source of truth for forecast-input assembly used by weather/dashboard forecast paths.
 *
 * Recurring merge policy (canonical):
 * - include all manual recurring rows
 * - include detected recurring rows only when confidence >= [HIGH_CONFIDENCE_THRESHOLD]
 * - dedupe restored stale manual rows by stable rule signature, not merchant alone
 * - manual rows take precedence only for the same stable rule signature
 *
 * ## Double-count risk (RESOLVED)
 *
 * Planned expenses that link to a recurring occurrence (via sourceOccurrenceKey)
 * are cross-deduplicated against materialized occurrences in the forecast window.
 * If a planned expense's sourceOccurrenceKey matches any PLANNED or PAID occurrence
 * generated by [RecurringLifecycleCoordinator.generateOccurrences], the planned
 * expense is excluded to avoid double-counting. Detected-only patterns (those
 * without manual rule counterparts) still flow through independently.
 *
 * ## FCST-10: Payday detection for income timing (planned)
 * Currently income timing uses a simple uniform spread, which produces inaccurate
 * cash-flow forecasts. The plan is to add payday detection that analyzes historical
 * deposit patterns:
 *
 * 1. **Identify recurring deposits**: Scan expenses with `transactionType = DEPOSIT`
 *    and group by source (payor name / merchant / transfer source).
 * 2. **Detect periodicity**: For each source, compute inter-deposit intervals and
 *    detect the dominant frequency (weekly, biweekly, semi-monthly, monthly).
 *    Use autocorrelation or FFT to identify the period even with modest jitter.
 * 3. **Predict next deposit**: Given the detected cadence and the last known deposit
 *    date, project the next expected deposit date and amount (using the rolling
 *    average of recent deposits from that source).
 * 4. **Integrate into forecast**: Add predicted deposits to [ForecastInput] as
 *    "income occurrences" so the [SynthesisEngine] can factor income timing into
 *    daily balance projections. Income confidence should decay for sources with
 *    fewer than 3 prior deposits.
 *
 * The detection logic belongs in a new `PaydayDetector` class; this assembler
 * would call it during [assemble] and merge the results into the forecast input.
 */
@Singleton
class ForecastInputAssembler @Inject constructor(
    private val timeProvider: TimeProvider,
    private val analyticsCurrencyNormalizer: AnalyticsCurrencyNormalizer,
    private val currencySettingsRepository: CurrencySettingsRepository,
    private val currencyConverter: CurrencyConverter,
    /** @suppress Coordinator injected for occurrence-driven dedup. */
    private val recurringLifecycleCoordinator: RecurringLifecycleCoordinator,
    /** @suppress DAO injected to query materialized occurrences for dedup. */
    private val recurringOccurrenceDao: RecurringOccurrenceDao,
    /** @suppress P6-CURRENT-024: guards read-only access to materialized occurrences. */
    private val databaseReadBarrier: DatabaseReadBarrier,
    /** @suppress P6-P1-08: canonical normalizer for multi-currency planned expense amounts. */
    private val moneyNormalizationEngine: MoneyNormalizationEngine =
        MoneyNormalizationEngine(currencyConverter)
) {
    /**
     * REC-20: Effective amount stability in recurring forecasting.
     *
     * All expense aggregation in this assembler uses [ExpenseSnapshot.effectiveAmount]
     * rather than the raw [ExpenseSnapshot.amount]. This is critical for stability
     * in recurring expense calculations because:
     *
     * - Shared expenses (group bills, split payments) have their per-person portion
     *   in [effectiveAmount], while [amount] is the full bill. Using the raw amount
     *   would overcount the user's actual recurring obligation.
     * - "Not mine" expenses ([isNotMine]) yield an effective amount of 0.0,
     *   correctly excluding them from totals without special-case logic.
     * - The derived [effectiveAmount] is deterministic for a given set of ownership
     *   flags, producing stable forecast baselines even when the raw `amount` field
     *   changes due to currency conversion or rounding.
     *
     * Always prefer [effectiveAmount] over [amount] when computing recurring
     * forecasts, budget projections, and spending trends.
     */

    data class ForecastInput(
        val pastSumDaily: List<Double>,
        val recurringPatterns: List<RecurringPattern>,
        val plannedExpenses: List<PlannedExpense>,
        val savingsGoals: List<SavingsGoal>,
        val budgetStatuses: List<BudgetStatusSnapshot>,
        val spendingPace: SpendingPace,
        /**
         * Materialised occurrences from manual recurring rules within the forecast window.
         * Downstream consumers (SynthesisEngine) should use this for accurate
         * per-occurrence committed/likely calculations instead of estimating
         * WEEKLY/BIWEEKLY counts from a single [RecurringPattern.nextExpectedDate].
         */
        val confirmedOccurrences: List<ConfirmedOccurrence> = emptyList(),
        val displayCurrency: String = "",
        val dataQuality: ForecastDataQuality = ForecastDataQuality()
    )

    fun mapExpenseSnapshots(
        expenses: List<com.yourname.expensetracker.data.database.entity.Expense>
    ): List<ExpenseSnapshot> = expenses.map { expense ->
        ExpenseSnapshot(
            id = expense.id,
            amount = expense.amount,
            effectiveAmount = expense.effectiveAmount,
            currency = expense.currency,
            merchant = expense.merchant,
            merchantKey = expense.merchantKey,
            transactionType = when (expense.transactionType) {
                TransactionType.PURCHASE -> DomainTransactionType.PURCHASE
                TransactionType.WITHDRAWAL -> DomainTransactionType.WITHDRAWAL
                TransactionType.TRANSFER -> DomainTransactionType.TRANSFER
                TransactionType.DEPOSIT -> DomainTransactionType.DEPOSIT
                TransactionType.UNKNOWN -> DomainTransactionType.UNKNOWN
            },
            date = expense.date,
            categoryId = expense.categoryId,
            isNotMine = expense.isNotMine,
            transferDirection = when (expense.transferDirection) {
                TransferDirection.INCOMING -> DomainTransferDirection.INCOMING
                TransferDirection.OUTGOING -> DomainTransferDirection.OUTGOING
                null -> null
            },
            notes = expense.notes
        )
    }

    /**
     * Maps entity [PlannedExpense] rows to domain [PlannedExpense] objects.
     *
     * ## FCST-1: Exclude FULFILLED planned expenses
     * Planned expenses with status == "FULFILLED" have already been linked to an
     * actual expense and must be excluded from forecast input to prevent
     * double-counting. Since the domain model does not carry a status field,
     * the filter is applied here at the mapping boundary.
     */
    fun mapPlannedExpenses(
        plannedEntities: List<com.yourname.expensetracker.data.database.entity.PlannedExpense>
    ): List<PlannedExpense> = plannedEntities
        .filter { entity -> entity.status == "PLANNED" }
        .map { entity ->
            PlannedExpense(
                id = entity.id,
                description = entity.description,
                amount = entity.amount,
                currency = entity.currency,
                date = entity.date,
                categoryId = entity.categoryId,
                isRecurring = entity.isRecurring,
                priority = when (entity.priority) {
                    EntityPlannedExpensePriority.MUST -> DomainPlannedExpensePriority.MUST
                    EntityPlannedExpensePriority.LIKELY -> DomainPlannedExpensePriority.LIKELY
                    EntityPlannedExpensePriority.OPTIONAL -> DomainPlannedExpensePriority.OPTIONAL
                },
                sourceOccurrenceKey = entity.sourceOccurrenceKey,
                status = entity.status
            )
        }

    fun mapBudgetSnapshots(budgetStatuses: List<BudgetStatus>): List<BudgetStatusSnapshot> =
        budgetStatuses.map { status ->
            BudgetStatusSnapshot(
                budgetCategoryId = status.budget.categoryId,
                budgetAmount = status.effectiveLimit,
                categoryName = status.category?.name,
                spentAmount = status.spentAmount,
                remainingAmount = status.remainingAmount,
                percentUsed = status.percentUsed.toDouble(),
                healthStatus = status.healthStatus,
                periodStart = status.periodStart,
                periodEnd = status.periodEnd
            )
        }

    fun mapSavingsGoals(goals: List<SavingsGoal>): List<SavingsGoal> = goals

    fun mergeRecurringPatterns(
        manualEntities: List<ManualRecurringExpense>,
        detectedPatterns: List<RecurringPattern>
    ): List<RecurringPattern> {
        val manualPatterns = mapConfirmedRecurringPatterns(manualEntities)

        val deduplicatedManualPatterns = dedupeManualPatternsBySignature(manualPatterns)
        val manualRuleSignatures = deduplicatedManualPatterns
            .mapTo(mutableSetOf()) { recurringRuleSignature(it) }
        val acceptedDetected = detectedPatterns
            .asSequence()
            .filter { it.confidence >= HIGH_CONFIDENCE_THRESHOLD }
            .filter { pattern -> recurringRuleSignature(pattern) !in manualRuleSignatures }
            .toList()

        // TODO P2-20: Merged patterns retain their original currency amounts. SynthesisEngine
        //  sums them raw without normalization to home currency. The proper fix requires
        //  injecting CurrencyConverter and converting each pattern's averageAmount to home
        //  currency here, which is tracked in the master plan as a larger refactor.
        return (deduplicatedManualPatterns + acceptedDetected).sortedByDescending { it.confidence }
    }

    fun mapConfirmedRecurringPatterns(
        manualEntities: List<ManualRecurringExpense>
    ): List<RecurringPattern> {
        val now = timeProvider.now()
        return manualEntities.map { manual ->
            RecurringPattern(
                id = manual.id,
                merchantName = manual.merchant,
                averageAmount = manual.amount,
                currency = manual.currency,
                frequency = manual.frequency,
                nextExpectedDate = rollNextExpectedDateForward(
                    nextExpectedDate = manual.nextDate,
                    frequency = manual.frequency,
                    now = now
                ),
                confidence = 1.0f,
                periodVarianceDays = 0,
                amountVariancePercent = 0.0,
                previousDates = emptyList()
            )
        }
    }

    fun dedupeConfirmedRecurringPatterns(
        manualPatterns: List<RecurringPattern>
    ): List<RecurringPattern> = dedupeManualPatternsBySignature(manualPatterns)

    private fun dedupeManualPatternsBySignature(
        manualPatterns: List<RecurringPattern>
    ): List<RecurringPattern> {
        return manualPatterns
            .groupBy { manualPatternSignature(it) }
            .values
            .map { patternsForSignature ->
                patternsForSignature.maxWithOrNull(
                    compareBy<RecurringPattern> { it.nextExpectedDate }
                        .thenBy { it.id ?: Long.MIN_VALUE }
                        .thenBy { it.merchantName }
                ) ?: patternsForSignature.first()
            }
    }

    private fun manualPatternSignature(pattern: RecurringPattern): ManualPatternSignature {
        return ManualPatternSignature(
            ruleSignature = recurringRuleSignature(pattern),
            categoryId = pattern.categoryId
        )
    }

    private fun recurringRuleSignature(pattern: RecurringPattern): RecurringRuleSignature {
        return RecurringRuleSignature(
            merchantKey = merchantKey(pattern.merchantName),
            frequency = pattern.frequency,
            amountMinor = (pattern.averageAmount * 100.0).roundToLong(),
            currency = pattern.currency.uppercase()
        )
    }

    fun buildPastSumDaily(expenses: List<ExpenseSnapshot>): List<Double> {
        val now = timeProvider.now()
        val monthStart = TimePeriodUtils.getStartOfMonth(now)
        val currentDayIndex = TimePeriodUtils.daysBetween(monthStart, now).coerceAtLeast(0)
        val amountByDay = DoubleArray(currentDayIndex + 1)

        expenses.forEach { expense ->
            if (expense.transactionType != DomainTransactionType.PURCHASE) return@forEach
            if (expense.isNotMine) return@forEach
            if (expense.date !in monthStart..now) return@forEach

            val dayIndex = TimePeriodUtils.daysBetween(monthStart, expense.date)
            if (dayIndex in amountByDay.indices) {
                amountByDay[dayIndex] += expense.effectiveAmount
            }
        }

        var runningTotal = 0.0
        return amountByDay.map { amount ->
            runningTotal += amount
            runningTotal
        }
    }

    fun buildSpendingPace(expenses: List<ExpenseSnapshot>, displayCurrency: String = "EUR"): SpendingPace {
        val now = timeProvider.now()
        val currentMonthStart = TimePeriodUtils.getStartOfMonth(now)
        val previousMonthStart = TimePeriodUtils.getStartOfMonth(TimePeriodUtils.addMonths(now, -1))
        val daysInMonth = TimePeriodUtils.getDaysInMonth(now)
        val daysElapsed = (TimePeriodUtils.daysBetween(currentMonthStart, now) + 1).coerceAtLeast(1)

        val monthSpent = expenses.sumOfIfOwnedPurchase { it.date in currentMonthStart..now }
        val previousMonthSpent = expenses.sumOfIfOwnedPurchase {
            it.date >= previousMonthStart && it.date < currentMonthStart
        }

        val averageMonthlyTotal = expenses
            .filter {
                it.transactionType == DomainTransactionType.PURCHASE &&
                    !it.isNotMine &&
                    it.date < currentMonthStart
            }
            .groupBy { "${TimePeriodUtils.getYear(it.date)}-${TimePeriodUtils.getMonth(it.date)}" }
            .values
            // SAFE: data normalized via AnalyticsCurrencyNormalizer at line 299 (inside assemble())
            .map { monthExpenses -> monthExpenses.sumOf { it.effectiveAmount } }
            .takeIf { it.isNotEmpty() }
            ?.average()

        val previousMonthDays = TimePeriodUtils.getDaysInMonth(previousMonthStart)
        val baselineDailyRate = if (previousMonthSpent > 0.0 && previousMonthDays > 0) {
            previousMonthSpent / previousMonthDays
        } else {
            0.0
        }

        val projectedTotal = SpendingPaceProjection.calculateProjectedTotal(
            monthSpent = monthSpent,
            daysElapsed = daysElapsed,
            daysInMonth = daysInMonth,
            baselineDailyRate = baselineDailyRate
        )

        val currentDailyRate = monthSpent / daysElapsed
        val pacePercentage = if (baselineDailyRate > 0.0) {
            (currentDailyRate / baselineDailyRate * 100.0).toFloat()
        } else {
            0f
        }

        val paceStatus = when {
            baselineDailyRate <= 0.0 -> PaceStatus.NO_BASELINE
            pacePercentage < PACE_UNDER_THRESHOLD -> PaceStatus.UNDER_PACE
            pacePercentage > PACE_OVER_THRESHOLD -> PaceStatus.OVER_PACE
            else -> PaceStatus.ON_PACE
        }

        return SpendingPace(
            currentMonthSpent = monthSpent,
            daysElapsed = daysElapsed,
            daysInMonth = daysInMonth,
            projectedTotal = projectedTotal,
            previousMonthTotal = previousMonthSpent.takeIf { it > 0.0 },
            averageMonthlyTotal = averageMonthlyTotal,
            pacePercentage = pacePercentage,
            paceStatus = paceStatus,
            displayCurrency = displayCurrency
        )
    }

    suspend fun assemble(
        expenses: List<ExpenseSnapshot>,
        manualRecurringEntities: List<ManualRecurringExpense>,
        detectedRecurringPatterns: List<RecurringPattern>,
        plannedExpenses: List<PlannedExpense>,
        savingsGoals: List<SavingsGoal>,
        budgetStatuses: List<BudgetStatusSnapshot>,
        homeCurrency: String? = null
    ): ForecastInput {
        // P6-CURRENT-025: Fail-closed home-currency resolution.
        // Mirrors CashFlowCalculator / BudgetRepository: use the typed
        // HomeCurrencyResolution and NEVER silently assume EUR. On Failed we
        // throw so the forecast does not proceed with a wrong-currency baseline.
        // Callers handle this fail-closed signal: FinancialWeatherRepository has a
        // .catch that surfaces "weather unavailable"; CalculateFinancialForecastUseCase
        // propagates it (same contract CashFlowCalculator already uses).
        val resolvedHomeCurrency = homeCurrency
            ?: when (val resolution = currencySettingsRepository.resolveHomeCurrency()) {
                is com.yourname.expensetracker.domain.currency.HomeCurrencyResolution.Resolved ->
                    resolution.currency.code
                is com.yourname.expensetracker.domain.currency.HomeCurrencyResolution.FirstRunDefault ->
                    resolution.currency.code
                is com.yourname.expensetracker.domain.currency.HomeCurrencyResolution.Failed ->
                    throw IllegalStateException(
                        "Home currency unavailable for forecast assembly: ${resolution.reason}"
                    )
            }
        val normalized = analyticsCurrencyNormalizer.normalizeSnapshots(expenses, resolvedHomeCurrency)
        val normalizedExpenses = normalized.includedExpenses

        // P6-CURRENT-024: READ paths must not write. Compute occurrences IN MEMORY
        // via the coordinator's read-only projection — no row materialization, no
        // lifecycle events, no write barrier. Materialization stays owned by
        // write-authorized paths (rule create/update, recurring screen, projection
        // service).
        val now = timeProvider.now()
        val forecastStart = TimePeriodUtils.getStartOfMonth(now)
        val forecastEnd = TimePeriodUtils.getEndOfMonth(now)

        val projectedOccurrences: List<RecurringOccurrence> = manualRecurringEntities
            .filter { it.isActive }
            .flatMap { rule ->
                try {
                    recurringLifecycleCoordinator.projectOccurrences(
                        ruleId = rule.id,
                        startDate = forecastStart,
                        endDate = forecastEnd
                    )
                } catch (e: Exception) {
                    if (e is kotlinx.coroutines.CancellationException) throw e
                    // Non-fatal: if one rule fails to project, continue with the rest
                    emptyList()
                }
            }

        // DBG-03: set of ACTIVE manual rule ids. The materialized read below MUST be
        // filtered to these ids so a PAUSED (isActive=false) rule's previously-materialized
        // PLANNED occurrences do not leak in as future obligations. projectOccurrences
        // already returns empty for inactive rules, but getByDateRange is not active-aware,
        // so the materialized side needs an explicit filter to match.
        val activeRuleIds: Set<Long> = manualRecurringEntities
            .filter { it.isActive }
            .map { it.id }
            .toSet()

        // ── Read already-materialized occurrences for dedup (READ-ONLY) ──────
        // Existing materialized rows (created by write-authorized paths) carry
        // authoritative status — including user overrides (SKIPPED/CANCELLED/
        // IGNORED) — so they take precedence over projections for the same key.
        // The read is guarded by the read barrier so it is blocked during restore.
        //
        // DBG-03: unlike CashFlowCalculator / FinancialStressForecastEngine, this read
        // previously applied NO sourceType/active filter. We now (a) restrict to
        // RECURRING_RULE rows and (b) restrict to ACTIVE rule ids, so paused rules and
        // non-rule occurrence sources cannot contaminate the forecast.
        // DBG-06: track barrier-block separately so we can flag the forecast as partial.
        var materializedReadBlocked = false
        val materializedOccurrences: List<RecurringOccurrence> = try {
            databaseReadBarrier.checkReadAllowed("ForecastInputAssembler.assemble.readOccurrences")
            recurringOccurrenceDao.getByDateRange(forecastStart, forecastEnd)
                .filter {
                    it.sourceType == RecurringLifecycleCoordinator.SOURCE_TYPE_RECURRING_RULE &&
                        it.sourceId in activeRuleIds
                }
        } catch (e: com.yourname.expensetracker.data.backup.DatabaseAccessBlockedException) {
            // DBG-06: restore barrier blocked the read. Projections bypass the barrier and
            // would surface PLANNED bills WITHOUT the materialized SKIPPED/CANCELLED
            // overrides → cancelled/skipped bills could transiently reappear. Mark the
            // forecast partial so downstream consumers treat the recurring section as
            // unreliable rather than authoritative.
            materializedReadBlocked = true
            emptyList()
        } catch (e: Exception) {
            if (e is kotlinx.coroutines.CancellationException) throw e
            emptyList()
        }

        // Merge by occurrenceKey: projections fill the window, materialized rows
        // override their keys. Because projection reuses the materializer's exact
        // key/expand logic, keys align and there is no divergence/double-count.
        val mergedOccurrencesByKey = LinkedHashMap<String, RecurringOccurrence>()
        for (occ in projectedOccurrences) mergedOccurrencesByKey[occ.occurrenceKey] = occ
        for (occ in materializedOccurrences) mergedOccurrencesByKey[occ.occurrenceKey] = occ
        val mergedOccurrences = mergedOccurrencesByKey.values.toList()

        // PLANNED keys serve two purposes:
        // 1) Cross-dedup planned expenses linked via sourceOccurrenceKey
        // 2) Provide confirmed occurrences for downstream occurrence-driven forecasting
        val plannedOccurrenceKeys = mergedOccurrences
            .filter { it.status == "PLANNED" }
            .map { it.occurrenceKey }.toSet()
        val confirmedOccurrences = mergedOccurrences
            .filter { it.status == "PLANNED" }
            .map { occ ->
                ConfirmedOccurrence(
                    dueDate = occ.dueDate,
                    expectedAmount = occ.expectedAmount,
                    expectedCurrency = occ.expectedCurrency,
                    merchant = occ.merchant,
                    categoryId = occ.categoryId,
                    status = occ.status
                )
            }

        val deduplicatedPlannedExpenses = plannedExpenses.filterNot { planned ->
            planned.sourceOccurrenceKey != null &&
                planned.sourceOccurrenceKey in plannedOccurrenceKeys
        }

        // ── Planned expense quality tracking ──────────────────────────────────
        val plannedDedupExcluded = plannedExpenses.size - deduplicatedPlannedExpenses.size
        var plannedConversionFailures = 0
        val plannedWarnings = mutableListOf<String>()

        // P6-P1-08: Normalize planned expenses through MoneyNormalizationEngine.
        // Group by currency and convert each group via the engine's canonical
        // bucket-level conversion (consistent rate-basis selection, failure tracking,
        // and metadata propagation).  Expenses in the home currency pass through
        // unchanged; foreign-currency groups use LATEST_AVAILABLE rate (appropriate for
        // future-dated planned items that have no transaction-date anchor).
        val normalizedPlannedExpenses = mutableListOf<PlannedExpense>()
        val byCurrency = deduplicatedPlannedExpenses.groupBy { it.currency.uppercase() }
        for ((currency, expensesInCurrency) in byCurrency) {
            if (currency.equals(resolvedHomeCurrency, ignoreCase = true)) {
                normalizedPlannedExpenses.addAll(
                    expensesInCurrency.map { it.copy(currency = resolvedHomeCurrency) }
                )
            } else {
                val totalAmount = expensesInCurrency.sumOf { it.amount }
                val bucketInput = MoneyBucketInput(
                    amount = totalAmount,
                    currency = CurrencyCode(currency),
                    transactionCount = expensesInCurrency.size
                )
                val aggregate = moneyNormalizationEngine.aggregateBuckets(
                    buckets = listOf(bucketInput),
                    homeCurrency = CurrencyCode(resolvedHomeCurrency),
                    rateBasis = RateBasis.LATEST_AVAILABLE,
                    bucketDatePolicy = BucketDatePolicy.Latest
                )
                if (!aggregate.isPartial && aggregate.conversionFailures.isEmpty()) {
                    // Distribute the converted total proportionally to each expense
                    val ratio = if (totalAmount > 0.0) aggregate.displayAmount / totalAmount else 0.0
                    for (pe in expensesInCurrency) {
                        normalizedPlannedExpenses.add(
                            pe.copy(amount = pe.amount * ratio, currency = resolvedHomeCurrency)
                        )
                    }
                } else {
                    plannedConversionFailures += expensesInCurrency.size
                    plannedWarnings.add(
                        "Planned expenses in $currency could not be converted to $resolvedHomeCurrency"
                    )
                }
            }
        }

        val totalPlannedExcluded = plannedDedupExcluded + plannedConversionFailures

        val inputCount = normalized.totalInputCount
        val excludedCount = normalized.excludedCount
        val missingRateWarnings = normalized.warnings.filter {
            it.type == AnalyticsConversionWarningType.MISSING_EXCHANGE_RATE
        }
        val confidencePenalty = if (inputCount > 0) {
            val excludedRatio = excludedCount.toDouble() / inputCount
            val missingRatio = missingRateWarnings.size.toDouble() / inputCount
            (excludedRatio * 0.35 + missingRatio * 0.10).coerceIn(0.0, 0.50)
        } else 0.0

        return ForecastInput(
            pastSumDaily = buildPastSumDaily(normalizedExpenses),
            recurringPatterns = mergeRecurringPatterns(
                manualEntities = manualRecurringEntities,
                detectedPatterns = detectedRecurringPatterns
            ),
            plannedExpenses = normalizedPlannedExpenses,
            savingsGoals = savingsGoals,
            budgetStatuses = budgetStatuses,
            spendingPace = buildSpendingPace(normalizedExpenses, resolvedHomeCurrency),
            confirmedOccurrences = confirmedOccurrences,
            displayCurrency = resolvedHomeCurrency,
            dataQuality = ForecastDataQuality(
                // DBG-06: also partial when the materialized read was barrier-blocked
                // (recurring overrides may be missing during restore).
                isPartial = excludedCount > 0 || totalPlannedExcluded > 0 || materializedReadBlocked,
                confidencePenalty = confidencePenalty,
                excludedActualCount = excludedCount,
                excludedPlannedCount = totalPlannedExcluded,
                excludedRecurringCount = 0,
                conversionWarnings = normalized.warnings.map { warning ->
                    "${warning.type.name}: ${warning.message}"
                } + plannedWarnings + (
                    if (materializedReadBlocked) {
                        listOf("RECURRING_OCCURRENCES_UNAVAILABLE: materialized occurrence read blocked during restore — recurring section may omit user overrides")
                    } else emptyList()
                )
            )
        )
    }

    /**
     * FCST-N3-FIXED: Consistent merchantKey fallback.
     *
     * Returns a stable merchant key for deduplication. When MerchantKeyGenerator
     * returns blank (e.g. because the merchant name is null or empty), we fall
     * back to the lowercase trimmed merchant name. This ensures that the fallback
     * is self-consistent across ALL forecast paths:
     *
     * - Forecast path A (Weather/FinancialWeatherRepository) uses this method
     *   via [recurringRuleSignature] → [merchantKey].
     * - Forecast path B (CalculateFinancialForecastUseCase) also uses the same
     *   [recurringRuleSignature] → [merchantKey] path.
     * - Expense-level merchant keys come from [ExpenseSnapshot.merchantKey]
     *   which was stored at write time via [MerchantKeyGenerator.generate].
     *
     * Both paths now converge on the same fallback logic. The previous
     * inconsistency occurred because some callers used `merchantKey ?: merchant`
     * (falling back to the raw merchant name) while others used
     * `MerchantKeyGenerator.generate(merchantName)` alone, leading to
     * different signature values for the same logical merchant.
     */
    private fun merchantKey(merchantName: String): String {
        return MerchantKeyGenerator.generate(merchantName)
            .takeIf { it.isNotBlank() }
            ?: merchantName.lowercase().trim()
    }

    private fun rollNextExpectedDateForward(
        nextExpectedDate: Long,
        frequency: com.yourname.expensetracker.domain.model.RecurrenceFrequency,
        now: Long
    ): Long {
        if (frequency.isIrregular) return nextExpectedDate

        val todayStart = TimePeriodUtils.getStartOfDay(now)
        var rolledDate = nextExpectedDate
        while (rolledDate < todayStart) {
            val candidate = RecurrenceCalculator.addFrequencyInterval(rolledDate, frequency)
            if (candidate == rolledDate) break
            rolledDate = candidate
        }

        return rolledDate
    }

    private fun List<ExpenseSnapshot>.sumOfIfOwnedPurchase(
        predicate: (ExpenseSnapshot) -> Boolean
    ): Double = filter {
        it.transactionType == DomainTransactionType.PURCHASE &&
            !it.isNotMine &&
            predicate(it)
    }
        // SAFE: data normalized via AnalyticsCurrencyNormalizer at line 299 (inside assemble())
        .sumOf { it.effectiveAmount }

    /**
     * CURR-587-06: Assemble forecast input from pre-normalized data.
     *
     * This bypasses the AnalyticsCurrencyNormalizer step since the expenses
     * are already normalized to home currency. The SpendingPace is also
     * taken directly from the input rather than recomputed.
     *
     * Planned expenses are normalized through MoneyNormalizationEngine
     * (same pattern as [assemble]) to convert foreign-currency amounts
     * into the home currency.
     */
    suspend fun assembleNormalized(
        input: NormalizedForecastInput
    ): ForecastInput {
        val resolvedHomeCurrency = input.homeCurrency.code

        // ── Planned expense normalization (mirrors assemble() pattern) ──────
        var plannedConversionFailures = 0
        val plannedWarnings = mutableListOf<String>()
        val normalizedPlannedExpenses = mutableListOf<PlannedExpense>()
        val byCurrency = input.plannedExpenses.groupBy { it.currency.uppercase() }
        for ((currency, expensesInCurrency) in byCurrency) {
            if (currency.equals(resolvedHomeCurrency, ignoreCase = true)) {
                normalizedPlannedExpenses.addAll(
                    expensesInCurrency.map { it.copy(currency = resolvedHomeCurrency) }
                )
            } else {
                val totalAmount = expensesInCurrency.sumOf { it.amount }
                val bucketInput = MoneyBucketInput(
                    amount = totalAmount,
                    currency = CurrencyCode(currency),
                    transactionCount = expensesInCurrency.size
                )
                val aggregate = moneyNormalizationEngine.aggregateBuckets(
                    buckets = listOf(bucketInput),
                    homeCurrency = CurrencyCode(resolvedHomeCurrency),
                    rateBasis = RateBasis.LATEST_AVAILABLE,
                    bucketDatePolicy = BucketDatePolicy.Latest
                )
                if (!aggregate.isPartial && aggregate.conversionFailures.isEmpty()) {
                    val ratio = if (totalAmount > 0.0) aggregate.displayAmount / totalAmount else 0.0
                    for (pe in expensesInCurrency) {
                        normalizedPlannedExpenses.add(
                            pe.copy(amount = pe.amount * ratio, currency = resolvedHomeCurrency)
                        )
                    }
                } else {
                    plannedConversionFailures += expensesInCurrency.size
                    plannedWarnings.add(
                        "Planned expenses in $currency could not be converted to $resolvedHomeCurrency"
                    )
                }
            }
        }

        val totalPlannedExcluded = plannedConversionFailures
        val mergedDataQuality = input.dataQuality.copy(
            isPartial = input.dataQuality.isPartial || totalPlannedExcluded > 0,
            excludedPlannedCount = input.dataQuality.excludedPlannedCount + totalPlannedExcluded,
            conversionWarnings = input.dataQuality.conversionWarnings + plannedWarnings
        )

        return ForecastInput(
            pastSumDaily = input.pastSumDaily,
            recurringPatterns = input.recurringPatterns,
            plannedExpenses = normalizedPlannedExpenses,
            savingsGoals = input.savingsGoals,
            budgetStatuses = input.budgetStatuses,
            spendingPace = input.spendingPace,
            confirmedOccurrences = emptyList(), // Can be populated via occurrence DAO if needed
            displayCurrency = resolvedHomeCurrency,
            dataQuality = mergedDataQuality
        )
    }

    companion object {
        const val HIGH_CONFIDENCE_THRESHOLD: Float = 0.70f
        private const val PACE_UNDER_THRESHOLD = 90f
        private const val PACE_OVER_THRESHOLD = 110f
    }

    private data class ManualPatternSignature(
        val ruleSignature: RecurringRuleSignature,
        val categoryId: Long?
    )

    private data class RecurringRuleSignature(
        val merchantKey: String,
        val frequency: com.yourname.expensetracker.domain.model.RecurrenceFrequency,
        val amountMinor: Long,
        val currency: String
    )
}
