package com.yourname.expensetracker.data.database

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.google.common.truth.Truth.assertThat
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.IOException

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [28])
class MigrationRegistrationTest {

    private val TEST_DB_NAME = "migration-registration-test"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    @Test
    fun `migration 120 to 121 creates group_lifecycle_events table`() {
        val db = helper.createDatabase(TEST_DB_NAME, 120)
        db.execSQL("INSERT INTO expenses (id, amount, currency, merchant, date, effectiveAmount, transactionType, isNotMine) VALUES (1, 100.0, 'EUR', 'Test', 1000, 100.0, 'PURCHASE', 0)")
        db.close()

        val migrated = helper.runMigrationsAndValidate(TEST_DB_NAME, 121, true, AppDatabase.MIGRATION_120_121)
        val cursor = migrated.query("SELECT * FROM group_lifecycle_events")
        assertThat(cursor.count).isEqualTo(0) // table exists but is empty
        cursor.close()
        migrated.close()
    }

    @Test
    fun `migration 119 to 121 creates both settlement and lifecycle tables`() {
        val db = helper.createDatabase(TEST_DB_NAME, 119)
        db.close()

        val migrated = helper.runMigrationsAndValidate(TEST_DB_NAME, 121, true, AppDatabase.MIGRATION_119_120, AppDatabase.MIGRATION_120_121)
        val cursor = migrated.query("SELECT name FROM sqlite_master WHERE type='table' AND name='group_settlements'")
        assertThat(cursor.count).isEqualTo(1)
        cursor.close()
        val cursor2 = migrated.query("SELECT name FROM sqlite_master WHERE type='table' AND name='group_lifecycle_events'")
        assertThat(cursor2.count).isEqualTo(1)
        cursor2.close()
        migrated.close()
    }

    @Test
    fun `ALL_MIGRATIONS includes migration 117 to 119`() {
        val migrations = AppDatabase.ALL_MIGRATIONS
        assertTrue(
            "Migration 117→118 must be registered in ALL_MIGRATIONS",
            migrations.any { it.startVersion == 117 && it.endVersion == 118 }
        )
        assertTrue(
            "Migration 118→119 must be registered in ALL_MIGRATIONS",
            migrations.any { it.startVersion == 118 && it.endVersion == 119 }
        )
    }

    @Test
    fun `ALL_MIGRATIONS includes migration 141 to 142`() {
        val migrations = AppDatabase.ALL_MIGRATIONS
        assertTrue(
            "Migration 141→142 must be registered in ALL_MIGRATIONS",
            migrations.any { it.startVersion == 141 && it.endVersion == 142 }
        )
    }

    @Test
    fun `ALL_MIGRATIONS includes migration 142 to 143`() {
        val migrations = AppDatabase.ALL_MIGRATIONS
        assertTrue(
            "Migration 142→143 must be registered in ALL_MIGRATIONS",
            migrations.any { it.startVersion == 142 && it.endVersion == 143 }
        )
    }

    /**
     * Strict-validate the combined Pipeline 6 migration: recreate budget_forecasts
     * with the four data-quality columns and the relaxed (CASCADE) budgets FK.
     *
     * NOTE: This validates the migrated database structurally against the
     * hand-authored 142.json bundle. The exported schema's identityHash must be
     * regenerated by the build (KSP) before the build-time schema verification
     * (verifyRoomSchemaSnapshots) passes; runMigrationsAndValidate itself is
     * structural and self-consistent on the bundle's hash.
     */
    @Test
    fun `migration 141 to 142 recreates budget_forecasts with quality columns and cascade fk`() {
        val db = helper.createDatabase(TEST_DB_NAME, 141)
        db.execSQL(
            "INSERT INTO budgets (id, categoryId, amount, period, periodMode, startDate, isActive, " +
                "notifyAtWarning, notifyAtCritical, rollover, rolloverDeficitTracking, currency, " +
                "currencyAssumption, createdAt) " +
                "VALUES (1, NULL, 500.0, 'MONTHLY', 'ROLLING', 1700000000000, 1, 0.75, 0.9, 0, 0, 'EUR', 'LEGACY_DEFAULT', 1700000000000)"
        )
        db.execSQL(
            "INSERT INTO budget_forecasts (id, budgetId, forecastDate, targetPeriodStart, targetPeriodEnd, " +
                "predictedSpending, predictedRemaining, confidenceScore, riskLevel, overspendProbability, " +
                "recommendationsJson, actualSpending, forecastAccuracy, currency, isActive, createdAt) " +
                "VALUES (1, 1, 1700000000000, 1700000000000, 1702592000000, 420.5, 79.5, 0.85, 'MEDIUM', 0.3, " +
                "NULL, NULL, NULL, 'EUR', 1, 1700000000000)"
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(TEST_DB_NAME, 142, true, AppDatabase.MIGRATION_141_142)

        // Legacy row preserved with the new quality columns defaulted.
        val cursor = migrated.query(
            "SELECT isPartial, excludedExpenseCount, qualityWarningsJson, rateBasis FROM budget_forecasts WHERE id = 1"
        )
        assertTrue(cursor.moveToFirst())
        assertThat(cursor.getInt(0)).isEqualTo(0)
        assertThat(cursor.getInt(1)).isEqualTo(0)
        assertThat(cursor.isNull(2)).isTrue()
        assertThat(cursor.isNull(3)).isTrue()
        cursor.close()
        migrated.close()
    }

    /**
     * S9 / P9-P1-09 (PR6): the additive 142→143 migration must create the
     * `warranty_reminder_deliveries` table (durable warranty-reminder sent-state).
     *
     * NOTE: [runMigrationsAndValidate] validates the migrated DB against the exported
     * 143.json schema bundle. That bundle is generated by KSP at build time — the build
     * must run once (regenerating the schema export) before this strict-validate test
     * passes. createDatabase(142) builds from the existing 142.json bundle, which already
     * contains the `warranties` parent table needed for the FK.
     */
    @Test
    fun `migration 142 to 143 creates warranty_reminder_deliveries table`() {
        val db = helper.createDatabase(TEST_DB_NAME, 142)
        // Seed a parent warranty so the new FK child can reference it.
        db.execSQL(
            "INSERT INTO warranties (id, receiptId, expenseId, productName, merchantName, " +
                "purchaseDate, warrantyDurationMonths, warrantyEndDate, warrantyType, status, " +
                "createdAt, updatedAt, autoDetected, extractionConfidence, extractionSource, needsReview) " +
                "VALUES (1, NULL, NULL, 'Laptop', 'Tech Store', 1700000000000, 24, 1800000000000, " +
                "'MANUFACTURER', 'ACTIVE', 1700000000000, 1700000000000, 0, 0.0, 'manual', 0)"
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(
            TEST_DB_NAME, 143, true, AppDatabase.MIGRATION_142_143
        )

        // Table exists and is empty.
        val cursor = migrated.query("SELECT * FROM warranty_reminder_deliveries")
        assertThat(cursor.count).isEqualTo(0)
        cursor.close()

        // A delivery row referencing the seeded warranty can be inserted.
        migrated.execSQL(
            "INSERT INTO warranty_reminder_deliveries " +
                "(warrantyId, windowDays, expiryDate, status, attemptCount, createdAt, updatedAt) " +
                "VALUES (1, 7, 1800000000000, 'SCHEDULED', 0, 1700000000000, 1700000000000)"
        )
        val seeded = migrated.query("SELECT warrantyId, windowDays, status FROM warranty_reminder_deliveries")
        assertTrue(seeded.moveToFirst())
        assertThat(seeded.getLong(0)).isEqualTo(1L)
        assertThat(seeded.getInt(1)).isEqualTo(7)
        assertThat(seeded.getString(2)).isEqualTo("SCHEDULED")
        seeded.close()
        migrated.close()
    }
}
