package com.yourname.expensetracker.domain.privacy

enum class PrivacyCapability {
    NOTIFICATION_CAPTURE,
    NOTIFICATION_PACKAGE_ALLOWLIST,
    CLOUD_AI_RECEIPT_ASSIST,
    CLOUD_AI_ITEM_CATEGORIZATION,
    CLOUD_AI_WARRANTY_EXTRACTION,
    CLOUD_AI_DAILY_BRIEFING,
    CLOUD_AI_GENERAL,
    RECEIPT_IMAGE_CLOUD_UPLOAD,
    EXTERNAL_GEOCODING,
    BACKGROUND_LOCATION_BACKFILL,
    DEVICE_GPS_LOCATION,
    RAWBACKUP_EXPORT,
    ENCRYPTED_BACKUP,
    RAW_NOTIFICATION_RETENTION,
    RAW_OCR_RETENTION,
    DEBUG_DATA_PERSISTENCE,
    OVERPASS_API,
    TIMBER_PII_LOGGING
}
